// lib/services/builtin_vocabulary.dart
// Eingebettete Vokabelliste: A1 bis C2 — 2296 Einträge
// Kein Internet erforderlich — vollständig offline nutzbar

class BuiltinVocabulary {
  static const List<List<String>> entries = [
    ['to be', 'sein'],
    ['to have', 'haben'],
    ['to do', 'tun|machen'],
    ['to say', 'sagen'],
    ['to go', 'gehen'],
    ['to get', 'bekommen|holen'],
    ['to make', 'machen'],
    ['to know', 'wissen|kennen'],
    ['to think', 'denken'],
    ['to take', 'nehmen'],
    ['to see', 'sehen'],
    ['to come', 'kommen'],
    ['to want', 'wollen'],
    ['to look', 'schauen|aussehen'],
    ['to use', 'benutzen|verwenden'],
    ['to find', 'finden'],
    ['to give', 'geben'],
    ['to tell', 'erzählen|sagen'],
    ['to work', 'arbeiten'],
    ['to call', 'anrufen|nennen'],
    ['to try', 'versuchen'],
    ['to ask', 'fragen'],
    ['to need', 'brauchen'],
    ['to feel', 'fühlen'],
    ['to become', 'werden'],
    ['to leave', 'verlassen|weggehen'],
    ['to put', 'legen|stellen'],
    ['to mean', 'bedeuten|meinen'],
    ['to keep', 'behalten|halten'],
    ['to let', 'lassen'],
    ['to begin', 'beginnen|anfangen'],
    ['to show', 'zeigen'],
    ['to hear', 'hören'],
    ['to play', 'spielen'],
    ['to run', 'laufen|rennen'],
    ['to move', 'bewegen|umziehen'],
    ['to live', 'leben|wohnen'],
    ['to believe', 'glauben'],
    ['to hold', 'halten'],
    ['to bring', 'bringen'],
    ['to happen', 'passieren|geschehen'],
    ['to write', 'schreiben'],
    ['to sit', 'sitzen'],
    ['to stand', 'stehen'],
    ['to lose', 'verlieren'],
    ['to pay', 'bezahlen'],
    ['to meet', 'treffen'],
    ['to include', 'einschließen|beinhalten'],
    ['to continue', 'weitermachen|fortsetzen'],
    ['to set', 'setzen|stellen'],
    ['to learn', 'lernen'],
    ['to change', 'ändern|wechseln'],
    ['to lead', 'führen'],
    ['to understand', 'verstehen'],
    ['to watch', 'beobachten|ansehen'],
    ['to follow', 'folgen'],
    ['to stop', 'stoppen|aufhören'],
    ['to create', 'erstellen|erschaffen'],
    ['to speak', 'sprechen'],
    ['to read', 'lesen'],
    ['to spend', 'ausgeben|verbringen'],
    ['to grow', 'wachsen'],
    ['to open', 'öffnen'],
    ['to close', 'schließen'],
    ['to walk', 'laufen|spazieren'],
    ['to win', 'gewinnen'],
    ['to offer', 'anbieten'],
    ['to remember', 'erinnern'],
    ['to love', 'lieben'],
    ['to consider', 'überlegen|berücksichtigen'],
    ['to appear', 'erscheinen|aussehen'],
    ['to buy', 'kaufen'],
    ['to wait', 'warten'],
    ['to serve', 'dienen|servieren'],
    ['to die', 'sterben'],
    ['to send', 'senden|schicken'],
    ['to expect', 'erwarten'],
    ['to build', 'bauen'],
    ['to stay', 'bleiben'],
    ['to fall', 'fallen'],
    ['to cut', 'schneiden'],
    ['to reach', 'erreichen'],
    ['to kill', 'töten'],
    ['to remain', 'bleiben|verbleiben'],
    ['to suggest', 'vorschlagen'],
    ['to raise', 'erheben|aufziehen'],
    ['to pass', 'bestehen|vorbeigehen'],
    ['to sell', 'verkaufen'],
    ['to decide', 'entscheiden'],
    ['to return', 'zurückkehren|zurückgeben'],
    ['to explain', 'erklären'],
    ['to hope', 'hoffen'],
    ['to develop', 'entwickeln'],
    ['to carry', 'tragen'],
    ['to break', 'brechen'],
    ['to receive', 'erhalten|bekommen'],
    ['to agree', 'zustimmen'],
    ['to support', 'unterstützen'],
    ['to hit', 'treffen|schlagen'],
    ['to produce', 'produzieren|herstellen'],
    ['to eat', 'essen'],
    ['to drink', 'trinken'],
    ['to sleep', 'schlafen'],
    ['to wake', 'aufwachen'],
    ['to drive', 'fahren'],
    ['to fly', 'fliegen'],
    ['to swim', 'schwimmen'],
    ['to cook', 'kochen'],
    ['to clean', 'putzen|reinigen'],
    ['to help', 'helfen'],
    ['to start', 'starten|beginnen'],
    ['to finish', 'beenden|fertigstellen'],
    ['to prepare', 'vorbereiten'],
    ['to share', 'teilen'],
    ['to visit', 'besuchen'],
    ['to travel', 'reisen'],
    ['to study', 'studieren|lernen'],
    ['to teach', 'lehren|unterrichten'],
    ['to answer', 'antworten'],
    ['to choose', 'wählen'],
    ['to check', 'prüfen|überprüfen'],
    ['to save', 'speichern|retten'],
    ['man', 'Mann'],
    ['woman', 'Frau'],
    ['child', 'Kind'],
    ['boy', 'Junge'],
    ['girl', 'Mädchen'],
    ['baby', 'Baby'],
    ['parent', 'Elternteil'],
    ['mother', 'Mutter'],
    ['father', 'Vater'],
    ['son', 'Sohn'],
    ['daughter', 'Tochter'],
    ['brother', 'Bruder'],
    ['sister', 'Schwester'],
    ['friend', 'Freund|Freundin'],
    ['family', 'Familie'],
    ['husband', 'Ehemann'],
    ['wife', 'Ehefrau'],
    ['person', 'Person'],
    ['people', 'Leute|Menschen'],
    ['adult', 'Erwachsener'],
    ['teacher', 'Lehrer|Lehrerin'],
    ['student', 'Schüler|Student'],
    ['doctor', 'Arzt|Ärztin'],
    ['boss', 'Chef|Chefin'],
    ['colleague', 'Kollege|Kollegin'],
    ['neighbor', 'Nachbar|Nachbarin'],
    ['house', 'Haus'],
    ['home', 'Zuhause|Heim'],
    ['room', 'Zimmer'],
    ['door', 'Tür'],
    ['window', 'Fenster'],
    ['table', 'Tisch'],
    ['chair', 'Stuhl'],
    ['bed', 'Bett'],
    ['kitchen', 'Küche'],
    ['bathroom', 'Badezimmer'],
    ['garden', 'Garten'],
    ['street', 'Straße'],
    ['car', 'Auto'],
    ['bus', 'Bus'],
    ['train', 'Zug'],
    ['plane', 'Flugzeug'],
    ['bike', 'Fahrrad'],
    ['food', 'Essen|Nahrung'],
    ['water', 'Wasser'],
    ['milk', 'Milch'],
    ['bread', 'Brot'],
    ['coffee', 'Kaffee'],
    ['tea', 'Tee'],
    ['wine', 'Wein'],
    ['beer', 'Bier'],
    ['juice', 'Saft'],
    ['apple', 'Apfel'],
    ['banana', 'Banane'],
    ['orange', 'Orange'],
    ['tomato', 'Tomate'],
    ['potato', 'Kartoffel'],
    ['rice', 'Reis'],
    ['meat', 'Fleisch'],
    ['fish', 'Fisch'],
    ['money', 'Geld'],
    ['time', 'Zeit'],
    ['day', 'Tag'],
    ['week', 'Woche'],
    ['month', 'Monat'],
    ['year', 'Jahr'],
    ['morning', 'Morgen'],
    ['evening', 'Abend'],
    ['night', 'Nacht'],
    ['number', 'Nummer|Zahl'],
    ['name', 'Name'],
    ['word', 'Wort'],
    ['book', 'Buch'],
    ['phone', 'Telefon'],
    ['computer', 'Computer'],
    ['internet', 'Internet'],
    ['big', 'groß'],
    ['small', 'klein'],
    ['long', 'lang'],
    ['short', 'kurz'],
    ['old', 'alt'],
    ['new', 'neu'],
    ['good', 'gut'],
    ['bad', 'schlecht'],
    ['hot', 'heiß'],
    ['cold', 'kalt'],
    ['fast', 'schnell'],
    ['slow', 'langsam'],
    ['hard', 'hart|schwer'],
    ['soft', 'weich|sanft'],
    ['easy', 'einfach|leicht'],
    ['difficult', 'schwierig|schwer'],
    ['happy', 'glücklich'],
    ['sad', 'traurig'],
    ['angry', 'wütend|ärgerlich'],
    ['tired', 'müde'],
    ['hungry', 'hungrig'],
    ['beautiful', 'schön|wunderschön'],
    ['ugly', 'hässlich'],
    ['clean', 'sauber'],
    ['dirty', 'schmutzig'],
    ['free', 'frei|kostenlos'],
    ['busy', 'beschäftigt'],
    ['ready', 'bereit|fertig'],
    ['open', 'offen|geöffnet'],
    ['closed', 'geschlossen'],
    ['right', 'richtig|recht'],
    ['wrong', 'falsch'],
    ['different', 'anders|verschieden'],
    ['same', 'gleich|derselbe'],
    ['important', 'wichtig'],
    ['interesting', 'interessant'],
    ['boring', 'langweilig'],
    ['funny', 'lustig|witzig'],
    ['serious', 'ernst|ernsthaft'],
    ['young', 'jung'],
    ['tall', 'groß|hochgewachsen'],
    ['heavy', 'schwer'],
    ['light', 'leicht|hell'],
    ['dark', 'dunkel'],
    ['bright', 'hell|leuchtend'],
    ['quiet', 'ruhig|leise'],
    ['loud', 'laut'],
    ['safe', 'sicher'],
    ['dangerous', 'gefährlich'],
    ['sick', 'krank'],
    ['healthy', 'gesund'],
    ['rich', 'reich'],
    ['poor', 'arm'],
    ['strong', 'stark'],
    ['weak', 'schwach'],
    ['true', 'wahr'],
    ['false', 'falsch'],
    ['real', 'echt|wirklich'],
    ['possible', 'möglich'],
    ['to achieve', 'erreichen|erzielen'],
    ['to affect', 'beeinflussen|betreffen'],
    ['to allow', 'erlauben|zulassen'],
    ['to apply', 'bewerben|anwenden'],
    ['to avoid', 'vermeiden'],
    ['to base', 'basieren|gründen'],
    ['to cause', 'verursachen'],
    ['to claim', 'behaupten|beanspruchen'],
    ['to collect', 'sammeln|abholen'],
    ['to compare', 'vergleichen'],
    ['to complete', 'vervollständigen|abschließen'],
    ['to confirm', 'bestätigen'],
    ['to connect', 'verbinden'],
    ['to contain', 'enthalten'],
    ['to control', 'kontrollieren|steuern'],
    ['to cover', 'decken|abdecken'],
    ['to deal', 'umgehen|handeln'],
    ['to describe', 'beschreiben'],
    ['to discuss', 'diskutieren|besprechen'],
    ['to discover', 'entdecken'],
    ['to divide', 'teilen|dividieren'],
    ['to doubt', 'zweifeln'],
    ['to earn', 'verdienen'],
    ['to enable', 'ermöglichen'],
    ['to encourage', 'ermutigen|fördern'],
    ['to enjoy', 'genießen'],
    ['to enter', 'eintreten|eingeben'],
    ['to establish', 'etablieren|gründen'],
    ['to examine', 'untersuchen|prüfen'],
    ['to exist', 'existieren|bestehen'],
    ['to express', 'ausdrücken'],
    ['to extend', 'verlängern|erweitern'],
    ['to face', 'gegenüberstehen|bewältigen'],
    ['to fail', 'scheitern|versagen'],
    ['to force', 'zwingen'],
    ['to forget', 'vergessen'],
    ['to gain', 'gewinnen|erlangen'],
    ['to improve', 'verbessern'],
    ['to increase', 'erhöhen|steigen'],
    ['to indicate', 'hinweisen|andeuten'],
    ['to introduce', 'vorstellen|einführen'],
    ['to join', 'beitreten|verbinden'],
    ['to judge', 'beurteilen|urteilen'],
    ['to manage', 'verwalten|schaffen'],
    ['to measure', 'messen'],
    ['to mention', 'erwähnen'],
    ['to obtain', 'erhalten|erlangen'],
    ['to occur', 'vorkommen|auftreten'],
    ['to plan', 'planen'],
    ['to prevent', 'verhindern|vorbeugen'],
    ['to provide', 'bereitstellen|liefern'],
    ['to reduce', 'reduzieren|verringern'],
    ['to refer', 'verweisen|beziehen'],
    ['to relate', 'beziehen|erzählen'],
    ['to remove', 'entfernen'],
    ['to replace', 'ersetzen'],
    ['to require', 'benötigen|erfordern'],
    ['to respond', 'reagieren|antworten'],
    ['to result', 'resultieren|führen zu'],
    ['to reveal', 'enthüllen|zeigen'],
    ['to seem', 'scheinen'],
    ['to solve', 'lösen'],
    ['to succeed', 'gelingen|Erfolg haben'],
    ['to suffer', 'leiden'],
    ['to supply', 'liefern|versorgen'],
    ['to survive', 'überleben'],
    ['to tend', 'neigen|pflegen'],
    ['to treat', 'behandeln'],
    ['to turn', 'drehen|wenden'],
    ['to vary', 'variieren|unterscheiden'],
    ['society', 'Gesellschaft'],
    ['economy', 'Wirtschaft'],
    ['government', 'Regierung'],
    ['policy', 'Politik|Richtlinie'],
    ['company', 'Unternehmen|Firma'],
    ['business', 'Geschäft|Unternehmen'],
    ['market', 'Markt'],
    ['industry', 'Industrie'],
    ['technology', 'Technologie'],
    ['science', 'Wissenschaft'],
    ['education', 'Bildung'],
    ['research', 'Forschung'],
    ['system', 'System'],
    ['process', 'Prozess|Verfahren'],
    ['service', 'Dienst|Service'],
    ['product', 'Produkt'],
    ['project', 'Projekt'],
    ['problem', 'Problem'],
    ['solution', 'Lösung'],
    ['question', 'Frage'],
    ['answer', 'Antwort'],
    ['information', 'Information'],
    ['idea', 'Idee'],
    ['plan', 'Plan'],
    ['result', 'Ergebnis|Resultat'],
    ['effect', 'Auswirkung|Effekt'],
    ['reason', 'Grund|Ursache'],
    ['way', 'Weg|Art'],
    ['point', 'Punkt'],
    ['fact', 'Tatsache|Fakt'],
    ['example', 'Beispiel'],
    ['part', 'Teil'],
    ['place', 'Ort|Platz'],
    ['case', 'Fall|Koffer'],
    ['area', 'Bereich|Gebiet'],
    ['group', 'Gruppe'],
    ['team', 'Team'],
    ['organization', 'Organisation'],
    ['country', 'Land'],
    ['city', 'Stadt'],
    ['region', 'Region'],
    ['environment', 'Umwelt|Umgebung'],
    ['community', 'Gemeinschaft'],
    ['culture', 'Kultur'],
    ['history', 'Geschichte'],
    ['development', 'Entwicklung'],
    ['situation', 'Situation|Lage'],
    ['position', 'Position|Stelle'],
    ['opportunity', 'Gelegenheit|Möglichkeit'],
    ['experience', 'Erfahrung|Erlebnis'],
    ['knowledge', 'Wissen|Kenntnisse'],
    ['skill', 'Fähigkeit|Fertigkeit'],
    ['quality', 'Qualität'],
    ['value', 'Wert'],
    ['cost', 'Kosten|Preis'],
    ['level', 'Ebene|Niveau'],
    ['rate', 'Rate|Tarif'],
    ['size', 'Größe'],
    ['type', 'Typ|Art'],
    ['form', 'Form'],
    ['model', 'Modell'],
    ['structure', 'Struktur'],
    ['method', 'Methode'],
    ['approach', 'Ansatz'],
    ['able', 'fähig|imstande'],
    ['available', 'verfügbar'],
    ['basic', 'grundlegend|einfach'],
    ['certain', 'sicher|bestimmt'],
    ['clear', 'klar|deutlich'],
    ['common', 'häufig|gewöhnlich'],
    ['complete', 'vollständig|komplett'],
    ['complex', 'komplex'],
    ['current', 'aktuell|derzeitig'],
    ['direct', 'direkt'],
    ['economic', 'wirtschaftlich|ökonomisch'],
    ['effective', 'effektiv|wirksam'],
    ['entire', 'ganz|vollständig'],
    ['equal', 'gleich|gleichberechtigt'],
    ['final', 'final|endgültig'],
    ['financial', 'finanziell'],
    ['general', 'allgemein'],
    ['global', 'global|weltweit'],
    ['human', 'menschlich|human'],
    ['individual', 'individuell|einzeln'],
    ['international', 'international'],
    ['local', 'lokal|örtlich'],
    ['major', 'bedeutend|groß'],
    ['medical', 'medizinisch'],
    ['modern', 'modern'],
    ['national', 'national'],
    ['natural', 'natürlich'],
    ['necessary', 'notwendig|nötig'],
    ['official', 'offiziell'],
    ['particular', 'besonders|speziell'],
    ['physical', 'physisch|körperlich'],
    ['political', 'politisch'],
    ['public', 'öffentlich'],
    ['recent', 'neulich|jüngst'],
    ['regional', 'regional'],
    ['social', 'sozial|gesellschaftlich'],
    ['special', 'besonders|speziell'],
    ['specific', 'spezifisch|bestimmmt'],
    ['technical', 'technisch'],
    ['total', 'gesamt|total'],
    ['traditional', 'traditionell'],
    ['various', 'verschiedene|diverse'],
    ['wide', 'breit|weit'],
    ['to acknowledge', 'anerkennen|bestätigen'],
    ['to acquire', 'erwerben|aneignen'],
    ['to advocate', 'befürworten|eintreten für'],
    ['to allocate', 'zuweisen|zuteilen'],
    ['to analyze', 'analysieren|untersuchen'],
    ['to anticipate', 'vorwegnehmen|erwarten'],
    ['to assert', 'behaupten|geltend machen'],
    ['to assess', 'bewerten|einschätzen'],
    ['to attribute', 'zuschreiben|zuordnen'],
    ['to characterize', 'charakterisieren'],
    ['to clarify', 'klären|klarstellen'],
    ['to collaborate', 'zusammenarbeiten'],
    ['to compile', 'zusammenstellen|kompilieren'],
    ['to comprise', 'umfassen|bestehen aus'],
    ['to concentrate', 'konzentrieren'],
    ['to conduct', 'durchführen|leiten'],
    ['to constitute', 'ausmachen|darstellen'],
    ['to constrain', 'einschränken|zwingen'],
    ['to construct', 'konstruieren|aufbauen'],
    ['to contradict', 'widersprechen'],
    ['to contribute', 'beitragen|beisteuern'],
    ['to convert', 'umwandeln|konvertieren'],
    ['to coordinate', 'koordinieren'],
    ['to correspond', 'entsprechen|korrespondieren'],
    ['to demonstrate', 'demonstrieren|zeigen'],
    ['to derive', 'ableiten|herleiten'],
    ['to detect', 'entdecken|feststellen'],
    ['to determine', 'bestimmen|ermitteln'],
    ['to differentiate', 'unterscheiden|differenzieren'],
    ['to distribute', 'verteilen'],
    ['to eliminate', 'eliminieren|beseitigen'],
    ['to emphasize', 'betonen|hervorheben'],
    ['to enhance', 'verbessern|steigern'],
    ['to evaluate', 'auswerten|bewerten'],
    ['to facilitate', 'erleichtern|fördern'],
    ['to formulate', 'formulieren'],
    ['to generate', 'erzeugen|generieren'],
    ['to highlight', 'hervorheben|betonen'],
    ['to identify', 'identifizieren|feststellen'],
    ['to illustrate', 'illustrieren|veranschaulichen'],
    ['to implement', 'umsetzen|implementieren'],
    ['to imply', 'implizieren|bedeuten'],
    ['to incorporate', 'einbeziehen|integrieren'],
    ['to interpret', 'interpretieren|deuten'],
    ['to investigate', 'untersuchen|erforschen'],
    ['to maintain', 'aufrechterhalten|pflegen'],
    ['to manipulate', 'manipulieren|handhaben'],
    ['to minimize', 'minimieren|verringern'],
    ['to modify', 'modifizieren|ändern'],
    ['to monitor', 'überwachen|beobachten'],
    ['to motivate', 'motivieren'],
    ['to negotiate', 'verhandeln'],
    ['to observe', 'beobachten|feststellen'],
    ['to optimize', 'optimieren'],
    ['to overcome', 'überwinden|bewältigen'],
    ['to perceive', 'wahrnehmen|erkennen'],
    ['to perform', 'durchführen|aufführen'],
    ['to predict', 'vorhersagen'],
    ['to prioritize', 'priorisieren|vorrangig behandeln'],
    ['to promote', 'fördern|bewerben'],
    ['to propose', 'vorschlagen'],
    ['to pursue', 'verfolgen|anstreben'],
    ['to recognize', 'erkennen|anerkennen'],
    ['to recommend', 'empfehlen'],
    ['to regulate', 'regulieren|kontrollieren'],
    ['to reinforce', 'verstärken|bekräftigen'],
    ['to reject', 'ablehnen|verwerfen'],
    ['to rely', 'sich verlassen|vertrauen'],
    ['to resolve', 'lösen|klären'],
    ['to restrict', 'einschränken|begrenzen'],
    ['to retain', 'behalten|aufrechterhalten'],
    ['to simulate', 'simulieren|nachahmen'],
    ['to specify', 'spezifizieren|angeben'],
    ['to stabilize', 'stabilisieren'],
    ['to stimulate', 'stimulieren|anregen'],
    ['to strengthen', 'stärken|festigen'],
    ['to submit', 'einreichen|unterwerfen'],
    ['to sustain', 'aufrechterhalten|stützen'],
    ['to tackle', 'angehen|anpacken'],
    ['to transform', 'transformieren|umwandeln'],
    ['to trigger', 'auslösen|anstoßen'],
    ['to undermine', 'untergraben|schwächen'],
    ['to utilize', 'nutzen|verwenden'],
    ['to validate', 'validieren|bestätigen'],
    ['to verify', 'überprüfen|verifizieren'],
    ['assumption', 'Annahme|Voraussetzung'],
    ['aspect', 'Aspekt|Gesichtspunkt'],
    ['benefit', 'Vorteil|Nutzen'],
    ['challenge', 'Herausforderung'],
    ['circumstance', 'Umstand|Umstände'],
    ['component', 'Komponente|Bestandteil'],
    ['concept', 'Konzept|Begriff'],
    ['consequence', 'Konsequenz|Folge'],
    ['constraint', 'Einschränkung|Zwang'],
    ['context', 'Kontext|Zusammenhang'],
    ['contribution', 'Beitrag'],
    ['controversy', 'Kontroverse|Streit'],
    ['criteria', 'Kriterien'],
    ['data', 'Daten'],
    ['debate', 'Debatte|Diskussion'],
    ['decade', 'Jahrzehnt'],
    ['definition', 'Definition'],
    ['dimension', 'Dimension|Ausmaß'],
    ['distinction', 'Unterschied|Unterscheidung'],
    ['diversity', 'Vielfalt|Diversität'],
    ['domain', 'Bereich|Domäne'],
    ['evidence', 'Beweise|Belege'],
    ['evolution', 'Entwicklung|Evolution'],
    ['factor', 'Faktor'],
    ['feature', 'Merkmal|Funktion'],
    ['foundation', 'Grundlage|Fundament'],
    ['framework', 'Rahmen|Konzept'],
    ['function', 'Funktion|Aufgabe'],
    ['hypothesis', 'Hypothese'],
    ['impact', 'Auswirkung|Einfluss'],
    ['implication', 'Implikation|Konsequenz'],
    ['initiative', 'Initiative|Maßnahme'],
    ['innovation', 'Innovation'],
    ['insight', 'Einblick|Erkenntnis'],
    ['integration', 'Integration'],
    ['interpretation', 'Interpretation|Deutung'],
    ['investment', 'Investition'],
    ['issue', 'Problem|Thema'],
    ['justification', 'Begründung|Rechtfertigung'],
    ['mechanism', 'Mechanismus'],
    ['motivation', 'Motivation'],
    ['objective', 'Ziel|Zweck'],
    ['outcome', 'Ergebnis|Resultat'],
    ['paradigm', 'Paradigma'],
    ['parameter', 'Parameter'],
    ['perspective', 'Perspektive|Sichtweise'],
    ['phenomenon', 'Phänomen'],
    ['potential', 'Potenzial'],
    ['principle', 'Prinzip|Grundsatz'],
    ['priority', 'Priorität|Vorrang'],
    ['procedure', 'Verfahren|Prozedur'],
    ['proportion', 'Verhältnis|Anteil'],
    ['regulation', 'Regulierung|Vorschrift'],
    ['relationship', 'Beziehung|Verhältnis'],
    ['requirement', 'Anforderung'],
    ['resource', 'Ressource'],
    ['restriction', 'Einschränkung'],
    ['role', 'Rolle'],
    ['scope', 'Umfang|Bereich'],
    ['significance', 'Bedeutung|Wichtigkeit'],
    ['source', 'Quelle'],
    ['strategy', 'Strategie'],
    ['theory', 'Theorie'],
    ['trend', 'Trend|Tendenz'],
    ['uncertainty', 'Unsicherheit'],
    ['abstract', 'abstrakt'],
    ['adequate', 'angemessen|ausreichend'],
    ['ambiguous', 'mehrdeutig|zweideutig'],
    ['appropriate', 'angemessen|geeignet'],
    ['coherent', 'kohärent|schlüssig'],
    ['compelling', 'überzeugend|zwingend'],
    ['comprehensive', 'umfassend|vollständig'],
    ['consistent', 'konsistent|beständig'],
    ['controversial', 'umstritten|kontrovers'],
    ['crucial', 'entscheidend|wesentlich'],
    ['deliberate', 'absichtlich|bewusst'],
    ['diverse', 'vielfältig|unterschiedlich'],
    ['dominant', 'dominierend|vorherrschend'],
    ['dynamic', 'dynamisch'],
    ['empirical', 'empirisch'],
    ['ethical', 'ethisch|moralisch'],
    ['excessive', 'übermäßig|übertrieben'],
    ['explicit', 'explizit|ausdrücklich'],
    ['fundamental', 'grundlegend|fundamental'],
    ['inevitable', 'unvermeidlich'],
    ['inherent', 'inhärent|innewohnend'],
    ['innovative', 'innovativ'],
    ['integrated', 'integriert'],
    ['intellectual', 'intellektuell'],
    ['intensive', 'intensiv'],
    ['logical', 'logisch'],
    ['marginal', 'geringfügig|marginal'],
    ['mature', 'reif|ausgereift'],
    ['mutual', 'gegenseitig'],
    ['ongoing', 'laufend|fortlaufend'],
    ['optimal', 'optimal'],
    ['precise', 'präzise|genau'],
    ['profound', 'tiefgründig|weitreichend'],
    ['rational', 'rational|vernünftig'],
    ['relevant', 'relevant|bedeutsam'],
    ['reliable', 'zuverlässig'],
    ['rigorous', 'streng|gründlich'],
    ['robust', 'robust|stabil'],
    ['significant', 'bedeutend|erheblich'],
    ['sophisticated', 'ausgereift|anspruchsvoll'],
    ['stable', 'stabil'],
    ['subjective', 'subjektiv'],
    ['subtle', 'subtil|fein'],
    ['sustainable', 'nachhaltig'],
    ['systematic', 'systematisch'],
    ['theoretical', 'theoretisch'],
    ['underlying', 'zugrunde liegend'],
    ['valid', 'gültig|valide'],
    ['viable', 'machbar|lebensfähig'],
    ['vulnerable', 'verletzlich|anfällig'],
    ['widespread', 'weit verbreitet'],
    ['tree', 'Baum'],
    ['forest', 'Wald'],
    ['mountain', 'Berg'],
    ['river', 'Fluss'],
    ['lake', 'See'],
    ['sea', 'Meer'],
    ['ocean', 'Ozean'],
    ['island', 'Insel'],
    ['beach', 'Strand'],
    ['desert', 'Wüste'],
    ['field', 'Feld'],
    ['flower', 'Blume'],
    ['grass', 'Gras'],
    ['plant', 'Pflanze'],
    ['animal', 'Tier'],
    ['dog', 'Hund'],
    ['cat', 'Katze'],
    ['bird', 'Vogel'],
    ['horse', 'Pferd'],
    ['cow', 'Kuh'],
    ['pig', 'Schwein'],
    ['sheep', 'Schaf'],
    ['lion', 'Löwe'],
    ['tiger', 'Tiger'],
    ['elephant', 'Elefant'],
    ['bear', 'Bär'],
    ['wolf', 'Wolf'],
    ['fox', 'Fuchs'],
    ['rabbit', 'Kaninchen|Hase'],
    ['mouse', 'Maus'],
    ['sun', 'Sonne'],
    ['moon', 'Mond'],
    ['star', 'Stern'],
    ['sky', 'Himmel'],
    ['cloud', 'Wolke'],
    ['rain', 'Regen'],
    ['snow', 'Schnee'],
    ['wind', 'Wind'],
    ['storm', 'Sturm'],
    ['ice', 'Eis'],
    ['fire', 'Feuer'],
    ['earth', 'Erde'],
    ['air', 'Luft'],
    ['shadow', 'Schatten'],
    ['stone', 'Stein'],
    ['sand', 'Sand'],
    ['soil', 'Boden|Erde'],
    ['climate', 'Klima'],
    ['weather', 'Wetter'],
    ['season', 'Jahreszeit'],
    ['spring', 'Frühling'],
    ['summer', 'Sommer'],
    ['autumn', 'Herbst'],
    ['winter', 'Winter'],
    ['temperature', 'Temperatur'],
    ['pollution', 'Verschmutzung|Umweltverschmutzung'],
    ['recycling', 'Recycling'],
    ['energy', 'Energie'],
    ['solar', 'solar|Sonnen-'],
    ['nuclear', 'nuklear|Kern-'],
    ['head', 'Kopf'],
    ['eye', 'Auge'],
    ['ear', 'Ohr'],
    ['nose', 'Nase'],
    ['mouth', 'Mund'],
    ['hand', 'Hand'],
    ['arm', 'Arm'],
    ['leg', 'Bein'],
    ['foot', 'Fuß'],
    ['back', 'Rücken'],
    ['heart', 'Herz'],
    ['brain', 'Gehirn'],
    ['blood', 'Blut'],
    ['bone', 'Knochen'],
    ['skin', 'Haut'],
    ['muscle', 'Muskel'],
    ['lung', 'Lunge'],
    ['stomach', 'Magen'],
    ['pain', 'Schmerz'],
    ['fever', 'Fieber'],
    ['flu', 'Grippe'],
    ['headache', 'Kopfschmerzen'],
    ['allergy', 'Allergie'],
    ['infection', 'Infektion'],
    ['medicine', 'Medizin|Medikament'],
    ['pill', 'Pille|Tablette'],
    ['surgery', 'Operation'],
    ['hospital', 'Krankenhaus'],
    ['emergency', 'Notfall'],
    ['diet', 'Diät|Ernährung'],
    ['exercise', 'Sport|Übung'],
    ['fitness', 'Fitness'],
    ['stress', 'Stress'],
    ['anxiety', 'Angst|Besorgnis'],
    ['depression', 'Depression'],
    ['therapy', 'Therapie'],
    ['journey', 'Reise|Fahrt'],
    ['trip', 'Ausflug|Reise'],
    ['holiday', 'Urlaub|Feiertag'],
    ['hotel', 'Hotel'],
    ['airport', 'Flughafen'],
    ['ticket', 'Ticket|Fahrkarte'],
    ['passport', 'Reisepass'],
    ['border', 'Grenze'],
    ['customs', 'Zoll'],
    ['luggage', 'Gepäck'],
    ['map', 'Karte|Landkarte'],
    ['route', 'Route|Weg'],
    ['distance', 'Entfernung|Distanz'],
    ['speed', 'Geschwindigkeit'],
    ['traffic', 'Verkehr'],
    ['bridge', 'Brücke'],
    ['tunnel', 'Tunnel'],
    ['port', 'Hafen'],
    ['station', 'Bahnhof'],
    ['restaurant', 'Restaurant'],
    ['menu', 'Speisekarte|Menü'],
    ['meal', 'Mahlzeit'],
    ['breakfast', 'Frühstück'],
    ['lunch', 'Mittagessen'],
    ['dinner', 'Abendessen'],
    ['dessert', 'Dessert|Nachtisch'],
    ['soup', 'Suppe'],
    ['salad', 'Salat'],
    ['sauce', 'Soße'],
    ['butter', 'Butter'],
    ['cheese', 'Käse'],
    ['egg', 'Ei'],
    ['chocolate', 'Schokolade'],
    ['sugar', 'Zucker'],
    ['salt', 'Salz'],
    ['pepper', 'Pfeffer'],
    ['vegetable', 'Gemüse'],
    ['fruit', 'Obst|Frucht'],
    ['nut', 'Nuss'],
    ['spice', 'Gewürz'],
    ['recipe', 'Rezept'],
    ['ingredient', 'Zutat'],
    ['flavor', 'Geschmack|Aroma'],
    ['organic', 'biologisch|organisch'],
    ['vegetarian', 'vegetarisch'],
    ['vegan', 'vegan'],
    ['apartment', 'Wohnung'],
    ['building', 'Gebäude'],
    ['floor', 'Stockwerk|Boden'],
    ['ceiling', 'Decke'],
    ['wall', 'Wand'],
    ['stairs', 'Treppe'],
    ['elevator', 'Aufzug|Fahrstuhl'],
    ['furniture', 'Möbel'],
    ['sofa', 'Sofa'],
    ['lamp', 'Lampe'],
    ['shelf', 'Regal'],
    ['mirror', 'Spiegel'],
    ['carpet', 'Teppich'],
    ['curtain', 'Vorhang'],
    ['heating', 'Heizung'],
    ['electricity', 'Elektrizität|Strom'],
    ['rent', 'Miete'],
    ['mortgage', 'Hypothek'],
    ['school', 'Schule'],
    ['university', 'Universität'],
    ['class', 'Klasse|Unterricht'],
    ['lesson', 'Lektion|Stunde'],
    ['subject', 'Fach|Thema'],
    ['exam', 'Prüfung|Examen'],
    ['grade', 'Note|Klasse'],
    ['diploma', 'Diplom|Abschluss'],
    ['degree', 'Abschluss|Grad'],
    ['professor', 'Professor|Professorin'],
    ['lecture', 'Vorlesung'],
    ['essay', 'Aufsatz'],
    ['assignment', 'Aufgabe|Hausaufgabe'],
    ['deadline', 'Frist|Abgabetermin'],
    ['language', 'Sprache'],
    ['grammar', 'Grammatik'],
    ['vocabulary', 'Vokabular|Wortschatz'],
    ['pronunciation', 'Aussprache'],
    ['translation', 'Übersetzung'],
    ['software', 'Software'],
    ['hardware', 'Hardware'],
    ['program', 'Programm'],
    ['application', 'Anwendung|App'],
    ['website', 'Website'],
    ['email', 'E-Mail'],
    ['message', 'Nachricht'],
    ['password', 'Passwort'],
    ['screen', 'Bildschirm'],
    ['keyboard', 'Tastatur'],
    ['network', 'Netzwerk'],
    ['download', 'Herunterladen'],
    ['upload', 'Hochladen'],
    ['digital', 'digital'],
    ['online', 'online'],
    ['social media', 'soziale Medien'],
    ['algorithm', 'Algorithmus'],
    ['artificial intelligence', 'künstliche Intelligenz'],
    ['bank', 'Bank'],
    ['account', 'Konto'],
    ['credit', 'Kredit'],
    ['debt', 'Schulden'],
    ['tax', 'Steuer'],
    ['profit', 'Gewinn'],
    ['loss', 'Verlust'],
    ['revenue', 'Umsatz|Einnahmen'],
    ['budget', 'Budget|Haushalt'],
    ['salary', 'Gehalt'],
    ['wage', 'Lohn'],
    ['contract', 'Vertrag'],
    ['deal', 'Geschäft|Vereinbarung'],
    ['trade', 'Handel'],
    ['export', 'Export'],
    ['import', 'Import'],
    ['currency', 'Währung'],
    ['stock', 'Aktie'],
    ['inflation', 'Inflation'],
    ['recession', 'Rezession'],
    ['law', 'Gesetz|Recht'],
    ['rule', 'Regel|Vorschrift'],
    ['freedom', 'Freiheit'],
    ['justice', 'Gerechtigkeit'],
    ['court', 'Gericht'],
    ['judge', 'Richter|Richterin'],
    ['lawyer', 'Anwalt|Anwältin'],
    ['crime', 'Verbrechen'],
    ['punishment', 'Strafe'],
    ['prison', 'Gefängnis'],
    ['police', 'Polizei'],
    ['election', 'Wahl'],
    ['vote', 'Stimme|abstimmen'],
    ['party', 'Partei'],
    ['democracy', 'Demokratie'],
    ['constitution', 'Verfassung'],
    ['parliament', 'Parlament'],
    ['minister', 'Minister|Ministerin'],
    ['president', 'Präsident'],
    ['art', 'Kunst'],
    ['music', 'Musik'],
    ['song', 'Lied'],
    ['film', 'Film'],
    ['theater', 'Theater'],
    ['concert', 'Konzert'],
    ['exhibition', 'Ausstellung'],
    ['painting', 'Gemälde|Malerei'],
    ['sculpture', 'Skulptur|Plastik'],
    ['photograph', 'Foto|Fotografie'],
    ['novel', 'Roman'],
    ['poem', 'Gedicht'],
    ['author', 'Autor|Schriftsteller'],
    ['artist', 'Künstler|Künstlerin'],
    ['actor', 'Schauspieler|Schauspielerin'],
    ['musician', 'Musiker|Musikerin'],
    ['director', 'Regisseur|Direktor'],
    ['instrument', 'Instrument'],
    ['sport', 'Sport'],
    ['game', 'Spiel'],
    ['match', 'Spiel|Match'],
    ['player', 'Spieler|Spielerin'],
    ['coach', 'Trainer|Trainerin'],
    ['stadium', 'Stadion'],
    ['competition', 'Wettbewerb'],
    ['championship', 'Meisterschaft'],
    ['training', 'Training'],
    ['tournament', 'Turnier'],
    ['referee', 'Schiedsrichter'],
    ['goal', 'Tor|Ziel'],
    ['score', 'Punktzahl|Ergebnis'],
    ['record', 'Rekord'],
    ['football', 'Fußball'],
    ['basketball', 'Basketball'],
    ['tennis', 'Tennis'],
    ['swimming', 'Schwimmen'],
    ['running', 'Laufen'],
    ['cycling', 'Radfahren'],
    ['hiking', 'Wandern'],
    ['climbing', 'Klettern'],
    ['dancing', 'Tanzen'],
    ['hobby', 'Hobby|Freizeitbeschäftigung'],
    ['entertainment', 'Unterhaltung'],
    ['to accept', 'akzeptieren|annehmen'],
    ['to add', 'hinzufügen|addieren'],
    ['to admit', 'zugeben|eingestehen'],
    ['to adopt', 'adoptieren|übernehmen'],
    ['to arrange', 'arrangieren|vereinbaren'],
    ['to attend', 'teilnehmen|besuchen'],
    ['to bite', 'beißen'],
    ['to blow', 'blasen'],
    ['to borrow', 'leihen|borgen'],
    ['to burn', 'brennen|verbrennen'],
    ['to catch', 'fangen|erwischen'],
    ['to celebrate', 'feiern'],
    ['to climb', 'klettern|steigen'],
    ['to copy', 'kopieren'],
    ['to count', 'zählen'],
    ['to cry', 'weinen|schreien'],
    ['to damage', 'beschädigen|schaden'],
    ['to dance', 'tanzen'],
    ['to deliver', 'liefern'],
    ['to draw', 'zeichnen'],
    ['to dress', 'anziehen'],
    ['to drop', 'fallen lassen|fallen'],
    ['to exchange', 'austauschen|wechseln'],
    ['to exercise', 'trainieren|Sport machen'],
    ['to fight', 'kämpfen|streiten'],
    ['to fill', 'füllen|ausfüllen'],
    ['to fix', 'reparieren|befestigen'],
    ['to form', 'formen|bilden'],
    ['to gather', 'sammeln|versammeln'],
    ['to greet', 'begrüßen'],
    ['to guess', 'raten|vermuten'],
    ['to hang', 'hängen'],
    ['to hate', 'hassen'],
    ['to hide', 'verstecken|verbergen'],
    ['to hug', 'umarmen'],
    ['to hunt', 'jagen'],
    ['to hurry', 'sich beeilen|eilen'],
    ['to hurt', 'verletzen|wehtun'],
    ['to imagine', 'sich vorstellen'],
    ['to inform', 'informieren|benachrichtigen'],
    ['to invite', 'einladen'],
    ['to jump', 'springen'],
    ['to kick', 'treten|kicken'],
    ['to kiss', 'küssen'],
    ['to knock', 'klopfen'],
    ['to land', 'landen'],
    ['to laugh', 'lachen'],
    ['to lift', 'heben'],
    ['to listen', 'hören|zuhören'],
    ['to lock', 'schließen|abschließen'],
    ['to miss', 'verpassen|vermissen'],
    ['to mix', 'mischen'],
    ['to order', 'bestellen|befehlen'],
    ['to own', 'besitzen'],
    ['to paint', 'malen|streichen'],
    ['to park', 'parken'],
    ['to pick', 'pflücken|auswählen'],
    ['to point', 'zeigen|hinweisen'],
    ['to pour', 'schütten|gießen'],
    ['to print', 'drucken'],
    ['to promise', 'versprechen'],
    ['to protect', 'schützen'],
    ['to prove', 'beweisen'],
    ['to pull', 'ziehen'],
    ['to push', 'drücken|schieben'],
    ['to record', 'aufnehmen|aufzeichnen'],
    ['to repeat', 'wiederholen'],
    ['to rest', 'ruhen|ausruhen'],
    ['to ride', 'reiten|fahren'],
    ['to ring', 'klingeln|läuten'],
    ['to roll', 'rollen'],
    ['to rub', 'reiben'],
    ['to shake', 'schütteln'],
    ['to shout', 'rufen|schreien'],
    ['to sign', 'unterschreiben|signieren'],
    ['to sing', 'singen'],
    ['to skip', 'überspringen|hüpfen'],
    ['to smell', 'riechen'],
    ['to smile', 'lächeln'],
    ['to smoke', 'rauchen'],
    ['to spell', 'buchstabieren'],
    ['to spread', 'verbreiten|ausbreiten'],
    ['to steal', 'stehlen'],
    ['to stick', 'kleben|stecken'],
    ['to stretch', 'strecken|dehnen'],
    ['to strike', 'treffen|streiken'],
    ['to struggle', 'kämpfen|sich abmühen'],
    ['to suck', 'saugen|lutschen'],
    ['to surf', 'surfen'],
    ['to swing', 'schwingen|schaukeln'],
    ['to taste', 'schmecken|kosten'],
    ['to throw', 'werfen'],
    ['to tie', 'binden'],
    ['to touch', 'berühren|anfassen'],
    ['to trade', 'handeln'],
    ['to trust', 'vertrauen'],
    ['to type', 'tippen'],
    ['to vote', 'wählen|abstimmen'],
    ['to wash', 'waschen'],
    ['to wear', 'tragen|anziehen'],
    ['to weigh', 'wiegen'],
    ['to whisper', 'flüstern'],
    ['to worry', 'sich sorgen'],
    ['to wrap', 'einwickeln'],
    ['to yell', 'schreien|brüllen'],
    ['zero', 'null'],
    ['one', 'eins|eine'],
    ['two', 'zwei'],
    ['three', 'drei'],
    ['four', 'vier'],
    ['five', 'fünf'],
    ['six', 'sechs'],
    ['seven', 'sieben'],
    ['eight', 'acht'],
    ['nine', 'neun'],
    ['ten', 'zehn'],
    ['hundred', 'hundert'],
    ['thousand', 'tausend'],
    ['million', 'Million'],
    ['half', 'Hälfte|halb'],
    ['quarter', 'Viertel'],
    ['dozen', 'Dutzend'],
    ['pair', 'Paar'],
    ['amount', 'Betrag|Menge'],
    ['quantity', 'Menge|Quantität'],
    ['average', 'Durchschnitt|Mittelwert'],
    ['percentage', 'Prozentsatz'],
    ['majority', 'Mehrheit'],
    ['minority', 'Minderheit'],
    ['red', 'rot'],
    ['blue', 'blau'],
    ['green', 'grün'],
    ['yellow', 'gelb'],
    ['black', 'schwarz'],
    ['white', 'weiß'],
    ['purple', 'lila|violett'],
    ['pink', 'rosa'],
    ['brown', 'braun'],
    ['grey', 'grau'],
    ['gold', 'golden|Gold'],
    ['silver', 'silbern|Silber'],
    ['colourful', 'bunt|farbenfroh'],
    ['hour', 'Stunde'],
    ['minute', 'Minute'],
    ['second', 'Sekunde'],
    ['weekend', 'Wochenende'],
    ['birthday', 'Geburtstag'],
    ['anniversary', 'Jahrestag'],
    ['century', 'Jahrhundert'],
    ['yesterday', 'gestern'],
    ['today', 'heute'],
    ['tomorrow', 'morgen'],
    ['soon', 'bald'],
    ['already', 'schon|bereits'],
    ['still', 'noch|immer noch'],
    ['ago', 'vor'],
    ['during', 'während'],
    ['since', 'seit'],
    ['until', 'bis'],
    ['often', 'oft'],
    ['always', 'immer'],
    ['never', 'nie'],
    ['sometimes', 'manchmal'],
    ['usually', 'normalerweise|gewöhnlich'],
    ['recently', 'kürzlich|neulich'],
    ['immediately', 'sofort|umgehend'],
    ['finally', 'endlich|schließlich'],
    ['suddenly', 'plötzlich'],
    ['gradually', 'allmählich'],
    ['left', 'links'],
    ['up', 'oben|hoch'],
    ['down', 'unten|runter'],
    ['front', 'vorne|Vorderseite'],
    ['top', 'oben|Spitze'],
    ['bottom', 'unten|Boden'],
    ['inside', 'innen|drinnen'],
    ['outside', 'außen|draußen'],
    ['above', 'über|oberhalb'],
    ['below', 'unter|unterhalb'],
    ['near', 'nah|in der Nähe'],
    ['far', 'weit|entfernt'],
    ['between', 'zwischen'],
    ['among', 'unter|zwischen'],
    ['around', 'um|herum'],
    ['through', 'durch'],
    ['across', 'über|quer'],
    ['along', 'entlang'],
    ['beside', 'neben'],
    ['north', 'Norden|nördlich'],
    ['south', 'Süden|südlich'],
    ['east', 'Osten|östlich'],
    ['west', 'Westen|westlich'],
    ['middle', 'Mitte|Mittelpunkt'],
    ['corner', 'Ecke'],
    ['narrow', 'schmal|eng'],
    ['deep', 'tief'],
    ['shallow', 'seicht|flach'],
    ['thick', 'dick'],
    ['thin', 'dünn'],
    ['full', 'voll'],
    ['empty', 'leer'],
    ['enough', 'genug'],
    ['too', 'zu|auch'],
    ['very', 'sehr'],
    ['quite', 'ziemlich'],
    ['rather', 'eher|ziemlich'],
    ['almost', 'fast|beinahe'],
    ['nearly', 'fast|beinahe'],
    ['shirt', 'Hemd|T-Shirt'],
    ['trousers', 'Hose'],
    ['dress', 'Kleid'],
    ['skirt', 'Rock'],
    ['jacket', 'Jacke'],
    ['coat', 'Mantel'],
    ['suit', 'Anzug'],
    ['shoes', 'Schuhe'],
    ['boots', 'Stiefel'],
    ['hat', 'Hut|Mütze'],
    ['bag', 'Tasche'],
    ['glasses', 'Brille'],
    ['watch', 'Uhr'],
    ['ring', 'Ring'],
    ['necklace', 'Halskette'],
    ['gloves', 'Handschuhe'],
    ['scarf', 'Schal'],
    ['uniform', 'Uniform'],
    ['fabric', 'Stoff|Gewebe'],
    ['cotton', 'Baumwolle'],
    ['leather', 'Leder'],
    ['wool', 'Wolle'],
    ['silk', 'Seide'],
    ['butterfly', 'Schmetterling'],
    ['bee', 'Biene'],
    ['ant', 'Ameise'],
    ['fly', 'Fliege'],
    ['spider', 'Spinne'],
    ['snake', 'Schlange'],
    ['frog', 'Frosch'],
    ['duck', 'Ente'],
    ['owl', 'Eule'],
    ['eagle', 'Adler'],
    ['deer', 'Reh|Hirsch'],
    ['squirrel', 'Eichhörnchen'],
    ['whale', 'Wal'],
    ['dolphin', 'Delfin'],
    ['shark', 'Hai'],
    ['crocodile', 'Krokodil'],
    ['branch', 'Ast|Zweig'],
    ['leaf', 'Blatt'],
    ['root', 'Wurzel'],
    ['seed', 'Same|Kern'],
    ['harvest', 'Ernte'],
    ['valley', 'Tal'],
    ['hill', 'Hügel'],
    ['cave', 'Höhle'],
    ['waterfall', 'Wasserfall'],
    ['volcano', 'Vulkan'],
    ['earthquake', 'Erdbeben'],
    ['flood', 'Überschwemmung'],
    ['drought', 'Dürre'],
    ['fog', 'Nebel'],
    ['thunder', 'Donner'],
    ['lightning', 'Blitz'],
    ['rainbow', 'Regenbogen'],
    ['horizon', 'Horizont'],
    ['garage', 'Garage'],
    ['basement', 'Keller'],
    ['attic', 'Dachboden'],
    ['balcony', 'Balkon'],
    ['terrace', 'Terrasse'],
    ['fence', 'Zaun'],
    ['gate', 'Tor|Pforte'],
    ['path', 'Pfad|Weg'],
    ['lawn', 'Rasen'],
    ['drawer', 'Schublade'],
    ['cupboard', 'Schrank'],
    ['wardrobe', 'Kleiderschrank'],
    ['fridge', 'Kühlschrank'],
    ['freezer', 'Gefrierschrank'],
    ['oven', 'Backofen|Ofen'],
    ['microwave', 'Mikrowelle'],
    ['dishwasher', 'Geschirrspüler'],
    ['sink', 'Waschbecken|Spüle'],
    ['tap', 'Hahn|Wasserhahn'],
    ['shower', 'Dusche'],
    ['bathtub', 'Badewanne'],
    ['toilet', 'Toilette'],
    ['towel', 'Handtuch'],
    ['blanket', 'Decke'],
    ['pillow', 'Kissen'],
    ['mattress', 'Matratze'],
    ['alarm clock', 'Wecker'],
    ['office', 'Büro'],
    ['meeting', 'Treffen|Besprechung'],
    ['report', 'Bericht'],
    ['presentation', 'Präsentation'],
    ['document', 'Dokument'],
    ['file', 'Datei|Akte'],
    ['folder', 'Ordner'],
    ['printer', 'Drucker'],
    ['scanner', 'Scanner'],
    ['manager', 'Manager|Vorgesetzte'],
    ['employee', 'Angestellte|Mitarbeiter'],
    ['employer', 'Arbeitgeber'],
    ['interview', 'Interview|Vorstellungsgespräch'],
    ['promotion', 'Beförderung'],
    ['career', 'Karriere|Laufbahn'],
    ['profession', 'Beruf'],
    ['occupation', 'Beschäftigung'],
    ['unemployed', 'arbeitslos'],
    ['retirement', 'Rente|Ruhestand'],
    ['vacation', 'Urlaub|Ferien'],
    ['conversation', 'Gespräch|Konversation'],
    ['discussion', 'Diskussion|Gespräch'],
    ['speech', 'Rede|Sprache'],
    ['argument', 'Argument|Streit'],
    ['opinion', 'Meinung|Ansicht'],
    ['advice', 'Rat|Ratschlag'],
    ['complaint', 'Beschwerde|Klage'],
    ['request', 'Bitte|Anfrage'],
    ['suggestion', 'Vorschlag'],
    ['comment', 'Kommentar|Anmerkung'],
    ['announcement', 'Ankündigung|Bekanntmachung'],
    ['warning', 'Warnung'],
    ['instruction', 'Anweisung|Anleitung'],
    ['description', 'Beschreibung'],
    ['explanation', 'Erklärung'],
    ['introduction', 'Einleitung|Vorstellung'],
    ['conclusion', 'Schlussfolgerung|Fazit'],
    ['summary', 'Zusammenfassung'],
    ['joy', 'Freude'],
    ['fear', 'Angst|Furcht'],
    ['anger', 'Wut|Ärger'],
    ['surprise', 'Überraschung'],
    ['disgust', 'Ekel'],
    ['shame', 'Scham'],
    ['guilt', 'Schuld'],
    ['envy', 'Neid'],
    ['jealousy', 'Eifersucht'],
    ['pride', 'Stolz'],
    ['hope', 'Hoffnung'],
    ['regret', 'Bedauern|Reue'],
    ['nostalgia', 'Nostalgie|Heimweh'],
    ['boredom', 'Langeweile'],
    ['patience', 'Geduld'],
    ['courage', 'Mut'],
    ['confidence', 'Selbstvertrauen|Zuversicht'],
    ['kindness', 'Freundlichkeit|Güte'],
    ['generosity', 'Großzügigkeit'],
    ['honesty', 'Ehrlichkeit'],
    ['loyalty', 'Loyalität|Treue'],
    ['responsibility', 'Verantwortung'],
    ['creativity', 'Kreativität'],
    ['curiosity', 'Neugier'],
    ['ambition', 'Ehrgeiz|Ambition'],
    ['determination', 'Entschlossenheit|Entscheidung'],
    ['humility', 'Bescheidenheit'],
    ['empathy', 'Empathie|Einfühlungsvermögen'],
    ['wisdom', 'Weisheit'],
    ['intelligence', 'Intelligenz'],
    ['talent', 'Talent'],
    ['ability', 'Fähigkeit'],
    ['accurate', 'genau|akkurat'],
    ['aggressive', 'aggressiv'],
    ['ambitious', 'ehrgeizig'],
    ['ancient', 'antik|uralt'],
    ['anonymous', 'anonym'],
    ['anxious', 'ängstlich|besorgt'],
    ['approximate', 'ungefähr|annähernd'],
    ['arrogant', 'arrogant'],
    ['artificial', 'künstlich'],
    ['atmospheric', 'atmosphärisch'],
    ['authentic', 'authentisch|echt'],
    ['aware', 'bewusst|aufmerksam'],
    ['awkward', 'unbeholfen|unangenehm'],
    ['balanced', 'ausgewogen|ausgeglichen'],
    ['bizarre', 'bizarr|seltsam'],
    ['brief', 'kurz|knapp'],
    ['brilliant', 'brilliant|glänzend'],
    ['capable', 'fähig|kompetent'],
    ['cautious', 'vorsichtig'],
    ['cheerful', 'fröhlich|heiter'],
    ['competitive', 'wettbewerbsfähig|ehrgeizig'],
    ['concerned', 'besorgt'],
    ['confident', 'selbstsicher|zuversichtlich'],
    ['confused', 'verwirrt'],
    ['conventional', 'konventionell'],
    ['cooperative', 'kooperativ'],
    ['critical', 'kritisch'],
    ['curious', 'neugierig'],
    ['decisive', 'entschlossen|entscheidend'],
    ['dedicated', 'engagiert|hingegeben'],
    ['detailed', 'detailliert'],
    ['diplomatic', 'diplomatisch'],
    ['disciplined', 'diszipliniert'],
    ['enthusiastic', 'begeistert|enthusiastisch'],
    ['essential', 'wesentlich|unerlässlich'],
    ['evident', 'offensichtlich|erkennbar'],
    ['exhausted', 'erschöpft'],
    ['extraordinary', 'außerordentlich|außergewöhnlich'],
    ['extreme', 'extrem'],
    ['familiar', 'vertraut|bekannt'],
    ['flexible', 'flexibel'],
    ['fluent', 'fließend'],
    ['formal', 'formell|förmlich'],
    ['fragile', 'zerbrechlich'],
    ['genuine', 'echt|aufrichtig'],
    ['grateful', 'dankbar'],
    ['guilty', 'schuldig'],
    ['harsh', 'hart|streng'],
    ['helpful', 'hilfsbereit|hilfreich'],
    ['honest', 'ehrlich'],
    ['hostile', 'feindlich'],
    ['ideal', 'ideal'],
    ['immediate', 'unmittelbar|sofortig'],
    ['impressive', 'beeindruckend'],
    ['independent', 'unabhängig|selbstständig'],
    ['informal', 'informell|zwanglos'],
    ['intense', 'intensiv'],
    ['isolated', 'isoliert'],
    ['keen', 'eifrig|scharf'],
    ['legitimate', 'legitim|rechtmäßig'],
    ['likely', 'wahrscheinlich'],
    ['limited', 'begrenzt|beschränkt'],
    ['lively', 'lebhaft|lebending'],
    ['loyal', 'loyal|treu'],
    ['massive', 'massiv|riesig'],
    ['meaningful', 'bedeutungsvoll'],
    ['modest', 'bescheiden'],
    ['mysterious', 'mysteriös|geheimnisvoll'],
    ['negative', 'negativ'],
    ['nervous', 'nervös'],
    ['neutral', 'neutral'],
    ['obvious', 'offensichtlich|klar'],
    ['passive', 'passiv'],
    ['patient', 'geduldig'],
    ['peaceful', 'friedlich|ruhig'],
    ['permanent', 'dauerhaft|permanent'],
    ['pleased', 'erfreut|zufrieden'],
    ['positive', 'positiv'],
    ['practical', 'praktisch'],
    ['professional', 'professionell|beruflich'],
    ['progressive', 'progressiv'],
    ['proper', 'richtig|angemessen'],
    ['proud', 'stolz'],
    ['rare', 'selten'],
    ['realistic', 'realistisch'],
    ['responsible', 'verantwortungsvoll'],
    ['sensitive', 'sensibel|empfindlich'],
    ['sharp', 'scharf'],
    ['shy', 'schüchtern'],
    ['similar', 'ähnlich'],
    ['simple', 'einfach|simpel'],
    ['skilled', 'fachkundig|geschickt'],
    ['smart', 'klug|intelligent'],
    ['strict', 'streng'],
    ['suitable', 'geeignet|passend'],
    ['surprised', 'überrascht'],
    ['talented', 'talentiert|begabt'],
    ['temporary', 'vorübergehend|zeitweilig'],
    ['tense', 'angespannt|gespannt'],
    ['terrible', 'schrecklich|furchtbar'],
    ['tight', 'eng|fest'],
    ['typical', 'typisch'],
    ['uncertain', 'unsicher|ungewiss'],
    ['uncomfortable', 'unangenehm|unbehaglich'],
    ['unique', 'einzigartig|einmalig'],
    ['unlikely', 'unwahrscheinlich'],
    ['unusual', 'ungewöhnlich'],
    ['upset', 'verärgert|bestürzt'],
    ['useful', 'nützlich|hilfreich'],
    ['violent', 'gewaltsam|heftig'],
    ['voluntary', 'freiwillig'],
    ['willing', 'bereit|gewillt'],
    ['worthy', 'würdig|wert'],
    ['abuse', 'Missbrauch'],
    ['access', 'Zugang|Zugriff'],
    ['achievement', 'Errungschaft|Leistung'],
    ['acquisition', 'Erwerb|Übernahme'],
    ['adaptation', 'Anpassung'],
    ['administration', 'Verwaltung|Administration'],
    ['advantage', 'Vorteil'],
    ['agenda', 'Tagesordnung|Agenda'],
    ['aid', 'Hilfe|Unterstützung'],
    ['alliance', 'Allianz|Bündnis'],
    ['alternative', 'Alternative'],
    ['analysis', 'Analyse'],
    ['approval', 'Genehmigung|Zustimmung'],
    ['authority', 'Autorität|Behörde'],
    ['awareness', 'Bewusstsein'],
    ['behavior', 'Verhalten'],
    ['capacity', 'Kapazität|Fähigkeit'],
    ['characteristic', 'Merkmal|Eigenschaft'],
    ['commitment', 'Verpflichtung|Engagement'],
    ['compliance', 'Einhaltung|Konformität'],
    ['compromise', 'Kompromiss'],
    ['condition', 'Bedingung|Zustand'],
    ['conflict', 'Konflikt'],
    ['consensus', 'Konsens|Einigkeit'],
    ['credibility', 'Glaubwürdigkeit'],
    ['crisis', 'Krise'],
    ['criticism', 'Kritik'],
    ['decline', 'Rückgang|Ablehnung'],
    ['dedication', 'Hingabe|Widmung'],
    ['deficit', 'Defizit|Mangel'],
    ['demand', 'Nachfrage|Forderung'],
    ['dependency', 'Abhängigkeit'],
    ['dialogue', 'Dialog|Gespräch'],
    ['disagreement', 'Meinungsverschiedenheit'],
    ['discipline', 'Disziplin|Fach'],
    ['disclosure', 'Offenlegung'],
    ['efficiency', 'Effizienz'],
    ['emergence', 'Entstehung|Aufkommen'],
    ['emphasis', 'Betonung|Schwerpunkt'],
    ['engagement', 'Engagement|Verpflichtung'],
    ['equality', 'Gleichheit|Gleichberechtigung'],
    ['equity', 'Gerechtigkeit|Eigenkapital'],
    ['exclusion', 'Ausgrenzung|Ausschluss'],
    ['expansion', 'Expansion|Erweiterung'],
    ['expertise', 'Fachwissen|Expertise'],
    ['exposure', 'Belastung|Bekanntheit'],
    ['extension', 'Erweiterung|Verlängerung'],
    ['failure', 'Versagen|Misserfolg'],
    ['flexibility', 'Flexibilität'],
    ['forecast', 'Prognose|Vorhersage'],
    ['gap', 'Lücke|Kluft'],
    ['governance', 'Regierungsführung'],
    ['growth', 'Wachstum'],
    ['guidance', 'Führung|Anleitung'],
    ['ideology', 'Ideologie'],
    ['inclusion', 'Eingliederung|Einbeziehung'],
    ['independence', 'Unabhängigkeit|Selbstständigkeit'],
    ['inequality', 'Ungleichheit'],
    ['influence', 'Einfluss'],
    ['infrastructure', 'Infrastruktur'],
    ['interaction', 'Interaktion'],
    ['involvement', 'Beteiligung|Einbeziehung'],
    ['leadership', 'Führung|Führungsqualität'],
    ['limitation', 'Einschränkung|Begrenzung'],
    ['maintenance', 'Wartung|Instandhaltung'],
    ['management', 'Management|Verwaltung'],
    ['manipulation', 'Manipulation'],
    ['measurement', 'Messung'],
    ['migration', 'Migration|Wanderung'],
    ['misunderstanding', 'Missverständnis'],
    ['negotiation', 'Verhandlung'],
    ['observation', 'Beobachtung'],
    ['opposition', 'Widerstand|Opposition'],
    ['participation', 'Teilnahme|Beteiligung'],
    ['perception', 'Wahrnehmung'],
    ['performance', 'Leistung|Auftritt'],
    ['persistence', 'Beharrlichkeit|Ausdauer'],
    ['population', 'Bevölkerung'],
    ['poverty', 'Armut'],
    ['prediction', 'Vorhersage|Prognose'],
    ['pressure', 'Druck'],
    ['privilege', 'Privileg|Vorrecht'],
    ['production', 'Produktion|Herstellung'],
    ['progress', 'Fortschritt'],
    ['proposal', 'Vorschlag'],
    ['protection', 'Schutz'],
    ['provision', 'Bereitstellung|Versorgung'],
    ['reaction', 'Reaktion'],
    ['recovery', 'Erholung|Genesung'],
    ['reform', 'Reform'],
    ['rejection', 'Ablehnung'],
    ['release', 'Veröffentlichung|Freilassung'],
    ['representation', 'Darstellung|Vertretung'],
    ['reputation', 'Ruf|Ansehen'],
    ['resistance', 'Widerstand'],
    ['revolution', 'Revolution'],
    ['risk', 'Risiko'],
    ['satisfaction', 'Zufriedenheit|Befriedigung'],
    ['security', 'Sicherheit'],
    ['selection', 'Auswahl'],
    ['status', 'Status|Stellung'],
    ['success', 'Erfolg'],
    ['tension', 'Spannung'],
    ['transformation', 'Transformation|Umwandlung'],
    ['transparency', 'Transparenz'],
    ['trust', 'Vertrauen'],
    ['unemployment', 'Arbeitslosigkeit'],
    ['unity', 'Einheit'],
    ['variation', 'Variation|Abweichung'],
    ['welfare', 'Wohlfahrt|Wohlbefinden'],
    ['toothache', 'Zahnschmerzen'],
    ['backache', 'Rückenschmerzen'],
    ['sore throat', 'Halsschmerzen'],
    ['runny nose', 'laufende Nase'],
    ['cough', 'Husten'],
    ['sneeze', 'Niesen'],
    ['bruise', 'Bluterguss|Prellung'],
    ['blister', 'Blase'],
    ['rash', 'Ausschlag'],
    ['wound', 'Wunde'],
    ['scar', 'Narbe'],
    ['fracture', 'Knochenbruch|Fraktur'],
    ['sprain', 'Verstauchung'],
    ['concussion', 'Gehirnerschütterung'],
    ['stroke', 'Schlaganfall'],
    ['diabetes', 'Diabetes|Zuckerkrankheit'],
    ['cancer', 'Krebs'],
    ['asthma', 'Asthma'],
    ['arthritis', 'Arthritis|Gelenkentzündung'],
    ['obesity', 'Übergewicht|Fettleibigkeit'],
    ['vaccination', 'Impfung'],
    ['prescription', 'Rezept|Verschreibung'],
    ['pharmacy', 'Apotheke'],
    ['symptom', 'Symptom'],
    ['diagnosis', 'Diagnose'],
    ['treatment', 'Behandlung'],
    ['ambulance', 'Krankenwagen'],
    ['nurse', 'Krankenpfleger|Krankenschwester'],
    ['surgeon', 'Chirurg|Chirurgin'],
    ['dentist', 'Zahnarzt|Zahnärztin'],
    ['physiotherapy', 'Physiotherapie'],
    ['mental health', 'psychische Gesundheit'],
    ['wellbeing', 'Wohlbefinden'],
    ['immune system', 'Immunsystem'],
    ['vitamin', 'Vitamin'],
    ['mineral', 'Mineral'],
    ['calorie', 'Kalorie'],
    ['protein', 'Protein|Eiweiß'],
    ['carbohydrate', 'Kohlenhydrat'],
    ['fat', 'Fett'],
    ['fiber', 'Ballaststoff'],
    ['experiment', 'Experiment|Versuch'],
    ['laboratory', 'Labor'],
    ['discovery', 'Entdeckung'],
    ['invention', 'Erfindung'],
    ['patent', 'Patent'],
    ['formula', 'Formel'],
    ['equation', 'Gleichung'],
    ['calculation', 'Berechnung'],
    ['statistics', 'Statistik'],
    ['probability', 'Wahrscheinlichkeit'],
    ['atom', 'Atom'],
    ['molecule', 'Molekül'],
    ['element', 'Element'],
    ['compound', 'Verbindung'],
    ['gravity', 'Schwerkraft|Gravitation'],
    ['force', 'Kraft'],
    ['density', 'Dichte'],
    ['frequency', 'Frequenz'],
    ['wavelength', 'Wellenlänge'],
    ['radiation', 'Strahlung'],
    ['magnetism', 'Magnetismus'],
    ['genetics', 'Genetik'],
    ['DNA', 'DNS|DNA'],
    ['cell', 'Zelle'],
    ['organism', 'Organismus'],
    ['species', 'Art|Spezies'],
    ['ecosystem', 'Ökosystem'],
    ['biodiversity', 'Biodiversität|Artenvielfalt'],
    ['photosynthesis', 'Photosynthese'],
    ['bacteria', 'Bakterien'],
    ['virus', 'Virus'],
    ['geology', 'Geologie'],
    ['astronomy', 'Astronomie'],
    ['physics', 'Physik'],
    ['chemistry', 'Chemie'],
    ['biology', 'Biologie'],
    ['mathematics', 'Mathematik'],
    ['geometry', 'Geometrie'],
    ['algebra', 'Algebra'],
    ['calculus', 'Infinitesimalrechnung'],
    ['volume', 'Volumen'],
    ['surface', 'Oberfläche|Fläche'],
    ['angle', 'Winkel'],
    ['diameter', 'Durchmesser'],
    ['radius', 'Radius'],
    ['smartphone', 'Smartphone'],
    ['tablet', 'Tablet'],
    ['laptop', 'Laptop'],
    ['desktop', 'Desktop'],
    ['processor', 'Prozessor'],
    ['memory', 'Speicher|Arbeitsspeicher'],
    ['storage', 'Speicher'],
    ['battery', 'Batterie|Akku'],
    ['charger', 'Ladegerät'],
    ['cable', 'Kabel'],
    ['wireless', 'drahtlos|kabellos'],
    ['Bluetooth', 'Bluetooth'],
    ['Wi-Fi', 'WLAN|Wi-Fi'],
    ['router', 'Router'],
    ['server', 'Server'],
    ['database', 'Datenbank'],
    ['backup', 'Sicherung|Backup'],
    ['update', 'Aktualisierung|Update'],
    ['install', 'installieren'],
    ['uninstall', 'deinstallieren'],
    ['notification', 'Benachrichtigung'],
    ['settings', 'Einstellungen'],
    ['username', 'Benutzername'],
    ['login', 'Anmeldung|Login'],
    ['privacy', 'Datenschutz|Privatsphäre'],
    ['encryption', 'Verschlüsselung'],
    ['hacker', 'Hacker'],
    ['malware', 'Malware|Schadsoftware'],
    ['spam', 'Spam'],
    ['firewall', 'Firewall'],
    ['browser', 'Browser'],
    ['search engine', 'Suchmaschine'],
    ['link', 'Link'],
    ['bookmark', 'Lesezeichen'],
    ['cache', 'Cache'],
    ['streaming', 'Streaming'],
    ['podcast', 'Podcast'],
    ['blog', 'Blog'],
    ['forum', 'Forum'],
    ['chat', 'Chat'],
    ['video call', 'Videoanruf'],
    ['screenshot', 'Screenshot|Bildschirmfoto'],
    ['emoji', 'Emoji'],
    ['hashtag', 'Hashtag'],
    ['like', 'Gefällt mir|Like'],
    ['share', 'teilen'],
    ['follow', 'folgen'],
    ['subscription', 'Abonnement'],
    ['content', 'Inhalt'],
    ['platform', 'Plattform'],
    ['influencer', 'Influencer'],
    ['e-commerce', 'E-Commerce|Online-Handel'],
    ['marketplace', 'Marktplatz'],
    ['delivery', 'Lieferung'],
    ['tracking', 'Verfolgung|Tracking'],
    ['machine learning', 'maschinelles Lernen'],
    ['robot', 'Roboter'],
    ['automation', 'Automatisierung'],
    ['virtual reality', 'virtuelle Realität'],
    ['augmented reality', 'erweiterte Realität'],
    ['blockchain', 'Blockchain'],
    ['cryptocurrency', 'Kryptowährung'],
    ['app', 'App|Anwendung'],
    ['supply', 'Angebot|Versorgung'],
    ['monopoly', 'Monopol'],
    ['merger', 'Fusion|Zusammenschluss'],
    ['shareholder', 'Aktionär'],
    ['dividend', 'Dividende'],
    ['interest', 'Zinsen|Interesse'],
    ['loan', 'Darlehen|Kredit'],
    ['insurance', 'Versicherung'],
    ['premium', 'Prämie|Aufpreis'],
    ['discount', 'Rabatt|Nachlass'],
    ['subsidy', 'Subvention'],
    ['tariff', 'Zoll|Tarif'],
    ['quota', 'Quote|Kontingent'],
    ['sanction', 'Sanktion'],
    ['GDP', 'BIP|Bruttoinlandsprodukt'],
    ['deflation', 'Deflation'],
    ['interest rate', 'Zinssatz'],
    ['exchange rate', 'Wechselkurs'],
    ['stock market', 'Börse|Aktienmarkt'],
    ['commodity', 'Rohstoff|Ware'],
    ['raw material', 'Rohstoff'],
    ['supply chain', 'Lieferkette'],
    ['manufacturer', 'Hersteller|Produzent'],
    ['distributor', 'Händler|Verteiler'],
    ['retailer', 'Einzelhändler'],
    ['wholesaler', 'Großhändler'],
    ['consumer', 'Verbraucher|Konsument'],
    ['brand', 'Marke'],
    ['trademark', 'Warenzeichen'],
    ['copyright', 'Urheberrecht'],
    ['franchise', 'Franchise'],
    ['startup', 'Startup|Gründung'],
    ['entrepreneur', 'Unternehmer'],
    ['venture capital', 'Risikokapital|Wagniskapital'],
    ['profit margin', 'Gewinnmarge'],
    ['overhead', 'Gemeinkosten|Betriebskosten'],
    ['expenditure', 'Ausgaben'],
    ['invoice', 'Rechnung|Faktura'],
    ['receipt', 'Quittung'],
    ['audit', 'Prüfung|Revision'],
    ['accountant', 'Buchhalter|Steuerberater'],
    ['balance sheet', 'Bilanz'],
    ['cash flow', 'Cashflow|Geldfluss'],
    ['continent', 'Kontinent'],
    ['Europe', 'Europa'],
    ['Asia', 'Asien'],
    ['Africa', 'Afrika'],
    ['America', 'Amerika'],
    ['Australia', 'Australien'],
    ['capital', 'Hauptstadt|Kapital'],
    ['tradition', 'Tradition'],
    ['festival', 'Festival|Fest'],
    ['monument', 'Denkmal'],
    ['landmark', 'Wahrzeichen'],
    ['tourist', 'Tourist|Touristin'],
    ['sightseeing', 'Sightseeing'],
    ['guide', 'Reiseführer|Führer'],
    ['brochure', 'Broschüre|Prospekt'],
    ['reservation', 'Reservierung'],
    ['check-in', 'Einchecken'],
    ['check-out', 'Auschecken'],
    ['reception', 'Rezeption|Empfang'],
    ['single room', 'Einzelzimmer'],
    ['double room', 'Doppelzimmer'],
    ['hostel', 'Jugendherberge|Hostel'],
    ['campsite', 'Campingplatz'],
    ['tent', 'Zelt'],
    ['sleeping bag', 'Schlafsack'],
    ['backpack', 'Rucksack'],
    ['suitcase', 'Koffer'],
    ['currency exchange', 'Geldwechsel'],
    ['cash', 'Bargeld'],
    ['credit card', 'Kreditkarte'],
    ['visa', 'Visum'],
    ['immigration', 'Einwanderung|Immigration'],
    ['jet lag', 'Jetlag'],
    ['time zone', 'Zeitzone'],
    ['destination', 'Reiseziel|Destination'],
    ['itinerary', 'Reiseplan|Route'],
    ['layover', 'Zwischenstopp'],
    ['departure', 'Abfahrt|Abflug'],
    ['arrival', 'Ankunft'],
    ['duty-free', 'zollfrei'],
    ['climate change', 'Klimawandel'],
    ['global warming', 'Erderwärmung'],
    ['greenhouse gas', 'Treibhausgas'],
    ['carbon dioxide', 'Kohlendioxid|CO2'],
    ['carbon footprint', 'CO2-Fußabdruck|Kohlenstoff-Fußabdruck'],
    ['renewable energy', 'erneuerbare Energie'],
    ['solar panel', 'Solaranlage|Solarpanel'],
    ['wind turbine', 'Windkraftanlage|Windrad'],
    ['fossil fuel', 'fossiler Brennstoff'],
    ['deforestation', 'Abholzung|Entwaldung'],
    ['habitat', 'Lebensraum|Habitat'],
    ['endangered species', 'bedrohte Art'],
    ['extinction', 'Aussterben'],
    ['conservation', 'Naturschutz|Erhaltung'],
    ['sustainability', 'Nachhaltigkeit'],
    ['waste', 'Abfall|Müll'],
    ['landfill', 'Deponie|Mülldeponie'],
    ['compost', 'Kompost'],
    ['biodegradable', 'biologisch abbaubar'],
    ['pesticide', 'Pestizid|Schädlingsbekämpfungsmittel'],
    ['fertilizer', 'Dünger'],
    ['irrigation', 'Bewässerung'],
    ['flooding', 'Überschwemmung'],
    ['erosion', 'Erosion|Abtragung'],
    ['ozone layer', 'Ozonschicht'],
    ['emissions', 'Emissionen|Abgase'],
    ['carbon neutral', 'kohlenstoffneutral'],
    ['net zero', 'Netto-Null'],
    ['ecological', 'ökologisch'],
    ['environmental', 'umweltbezogen|Umwelt-'],
    ['wildlife', 'Wildleben|Tierwelt'],
    ['curriculum', 'Lehrplan|Curriculum'],
    ['syllabus', 'Lehrplan|Kursinhalt'],
    ['semester', 'Semester'],
    ['term', 'Trimester|Begriff'],
    ['course', 'Kurs|Lehrgang'],
    ['module', 'Modul'],
    ['seminar', 'Seminar'],
    ['tutorial', 'Tutorium|Übung'],
    ['workshop', 'Workshop'],
    ['conference', 'Konferenz'],
    ['scholarship', 'Stipendium'],
    ['tuition', 'Unterricht|Studiengebühr'],
    ['pupil', 'Schüler|Schülerin'],
    ['undergraduate', 'Student im Grundstudium'],
    ['postgraduate', 'Postgraduierter'],
    ['thesis', 'Diplomarbeit|Abschlussarbeit'],
    ['dissertation', 'Dissertation'],
    ['supervisor', 'Betreuer|Vorgesetzte'],
    ['bibliography', 'Bibliografie|Literaturverzeichnis'],
    ['footnote', 'Fußnote'],
    ['peer review', 'Peer-Review'],
    ['citation', 'Zitat|Quellenangabe'],
    ['plagiarism', 'Plagiat'],
    ['critical thinking', 'kritisches Denken'],
    ['problem solving', 'Problemlösung'],
    ['collaboration', 'Zusammenarbeit|Kollaboration'],
    ['literacy', 'Lesekompetenz|Bildung'],
    ['numeracy', 'Rechenkompetenz'],
    ['qualification', 'Qualifikation|Abschluss'],
    ['certification', 'Zertifizierung'],
    ['internship', 'Praktikum'],
    ['apprenticeship', 'Ausbildung|Lehre'],
    ['distance learning', 'Fernunterricht'],
    ['e-learning', 'E-Learning'],
    ['blended learning', 'Blended Learning'],
    ['curriculum vitae', 'Lebenslauf'],
    ['citizen', 'Bürger|Bürgerin'],
    ['civil rights', 'Bürgerrechte'],
    ['human rights', 'Menschenrechte'],
    ['discrimination', 'Diskriminierung'],
    ['racism', 'Rassismus'],
    ['sexism', 'Sexismus'],
    ['oppression', 'Unterdrückung'],
    ['activism', 'Aktivismus'],
    ['protest', 'Protest|Demonstration'],
    ['amendment', 'Änderung|Zusatz'],
    ['legislation', 'Gesetzgebung'],
    ['welfare state', 'Wohlfahrtsstaat'],
    ['social security', 'Sozialversicherung'],
    ['pension', 'Rente|Pension'],
    ['healthcare', 'Gesundheitsversorgung'],
    ['public transport', 'öffentlicher Nahverkehr'],
    ['urbanization', 'Urbanisierung|Verstädterung'],
    ['emigration', 'Auswanderung'],
    ['asylum', 'Asyl'],
    ['refugee', 'Flüchtling'],
    ['multicultural', 'multikulturell'],
    ['tolerance', 'Toleranz'],
    ['diplomacy', 'Diplomatie'],
    ['treaty', 'Vertrag|Abkommen'],
    ['war', 'Krieg'],
    ['peace', 'Frieden'],
    ['ceasefire', 'Waffenstillstand'],
    ['embargo', 'Embargo'],
    ['veto', 'Veto'],
    ['referendum', 'Referendum|Volksabstimmung'],
    ['corruption', 'Korruption'],
    ['accountability', 'Rechenschaftspflicht'],
    ['bureaucracy', 'Bürokratie'],
    ['to give up', 'aufgeben'],
    ['to give in', 'nachgeben'],
    ['to give away', 'verschenken|verraten'],
    ['to take off', 'abheben|ausziehen'],
    ['to take on', 'übernehmen|einstellen'],
    ['to take over', 'übernehmen'],
    ['to take up', 'anfangen|beanspruchen'],
    ['to make up', 'erfinden|sich versöhnen'],
    ['to make out', 'verstehen|erkennen'],
    ['to make up for', 'wettmachen|kompensieren'],
    ['to bring up', 'aufziehen|zur Sprache bringen'],
    ['to bring about', 'herbeiführen|verursachen'],
    ['to bring back', 'zurückbringen'],
    ['to bring down', 'senken|stürzen'],
    ['to turn out', 'sich herausstellen'],
    ['to turn up', 'auftauchen|erhöhen'],
    ['to turn down', 'ablehnen|leiser stellen'],
    ['to turn off', 'ausschalten'],
    ['to turn on', 'einschalten'],
    ['to turn into', 'sich verwandeln in'],
    ['to carry out', 'durchführen'],
    ['to carry on', 'fortfahren|weitermachen'],
    ['to carry over', 'übertragen|mitnehmen'],
    ['to set up', 'gründen|einrichten'],
    ['to set out', 'aufbrechen|darlegen'],
    ['to set back', 'zurückwerfen|verzögern'],
    ['to set aside', 'beiseitelegen|reservieren'],
    ['to look up', 'nachschlagen|nach oben schauen'],
    ['to look out', 'aufpassen|Ausschau halten'],
    ['to look into', 'untersuchen|nachforschen'],
    ['to look forward to', 'sich freuen auf'],
    ['to look after', 'sich kümmern um'],
    ['to look back', 'zurückblicken'],
    ['to come across', 'stoßen auf|wirken'],
    ['to come up with', 'sich einfallen lassen'],
    ['to come down to', 'hinauslaufen auf'],
    ['to come along', 'mitkommen|vorankommen'],
    ['to run out of', 'ausgehen von'],
    ['to run into', 'treffen|stoßen auf'],
    ['to run away', 'weglaufen|fliehen'],
    ['to run through', 'durchgehen|durchlaufen'],
    ['to break down', 'zusammenbrechen|aufschlüsseln'],
    ['to break out', 'ausbrechen'],
    ['to break through', 'durchbrechen'],
    ['to break up', 'sich trennen|zerbrechen'],
    ['to break in', 'einbrechen|unterbrechen'],
    ['to get along', 'auskommen|vorankommen'],
    ['to get over', 'überwinden'],
    ['to get through', 'durchkommen|schaffen'],
    ['to get rid of', 'loswerden'],
    ['to get away', 'entkommen'],
    ['to get back', 'zurückbekommen|zurückkehren'],
    ['to get across', 'rüberbringen|überqueren'],
    ['to put off', 'verschieben|abschrecken'],
    ['to put up with', 'ertragen|sich abfinden mit'],
    ['to put forward', 'vorschlagen|vorbringen'],
    ['to put down', 'niederschreiben|demütigen'],
    ['to put out', 'löschen|ausschalten'],
    ['to put aside', 'beiseitelegen'],
    ['to fall apart', 'auseinanderfallen|zusammenbrechen'],
    ['to fall behind', 'zurückfallen|im Rückstand sein'],
    ['to fall through', 'scheitern|ins Wasser fallen'],
    ['to fall for', 'hereinfallen auf|sich verlieben in'],
    ['to stand for', 'stehen für|vertreten'],
    ['to stand out', 'herausstechen|auffallen'],
    ['to stand up for', 'eintreten für|verteidigen'],
    ['to stand by', 'beistehen|halten zu'],
    ['to go through', 'durchmachen|durchgehen'],
    ['to go over', 'durchgehen|überprüfen'],
    ['to go along with', 'mitmachen|zustimmen'],
    ['to go back on', 'brechen|zurückziehen'],
    ['to hold on', 'festhalten|warten'],
    ['to hold back', 'zurückhalten'],
    ['to hold up', 'aufhalten|stützen'],
    ['to hold out', 'ausharren|standhalten'],
    ['to work out', 'ausarbeiten|sich herausstellen|trainieren'],
    ['to work through', 'durcharbeiten'],
    ['to work around', 'umgehen'],
    ['to keep up', 'mithalten|aufrechterhalten'],
    ['to keep on', 'weitermachen'],
    ['to keep back', 'zurückhalten'],
    ['to keep from', 'fernhalten|verhindern'],
    ['to show up', 'auftauchen|erscheinen'],
    ['to show off', 'angeben|vorführen'],
    ['to back up', 'sichern|unterstützen|zurücksetzen'],
    ['to back down', 'nachgeben|zurückrudern'],
    ['to back off', 'zurückweichen|Abstand nehmen'],
    ['accessible', 'zugänglich|barrierefrei'],
    ['accountable', 'rechenschaftspflichtig|verantwortlich'],
    ['adaptable', 'anpassungsfähig'],
    ['affectionate', 'liebevoll|zärtlich'],
    ['affluent', 'wohlhabend|vermögend'],
    ['alarming', 'beunruhigend|alarmierend'],
    ['appealing', 'ansprechend|attraktiv'],
    ['assertive', 'selbstbewusst|durchsetzungsstark'],
    ['attentive', 'aufmerksam'],
    ['charitable', 'wohltätig|großherzig'],
    ['civic', 'bürgerlich|städtisch'],
    ['compact', 'kompakt|platzsparend'],
    ['compassionate', 'mitfühlend'],
    ['compatible', 'kompatibel|vereinbar'],
    ['complacent', 'selbstgefällig|träge'],
    ['concise', 'prägnant|knapp'],
    ['conducive', 'förderlich|zuträglich'],
    ['contentious', 'strittig|umstritten'],
    ['contradictory', 'widersprüchlich'],
    ['convenient', 'bequem|günstig'],
    ['convincing', 'überzeugend'],
    ['corrupt', 'korrupt'],
    ['crafty', 'listig|geschickt'],
    ['credible', 'glaubwürdig'],
    ['cynical', 'zynisch'],
    ['demanding', 'anspruchsvoll|fordernd'],
    ['depressing', 'deprimierend'],
    ['devoted', 'ergeben|hingegeben'],
    ['diligent', 'fleißig'],
    ['disruptive', 'störend|revolutionär'],
    ['distinguished', 'angesehen|namhaft'],
    ['durable', 'haltbar|langlebig'],
    ['eager', 'eifrig|begierig'],
    ['elaborate', 'ausgearbeitet|aufwendig'],
    ['eloquent', 'beredt|redegewandt'],
    ['encouraging', 'ermutigend'],
    ['engaging', 'ansprechend|fesselnd'],
    ['enterprising', 'unternehmungslustig'],
    ['evolving', 'sich entwickelnd'],
    ['exaggerated', 'übertrieben'],
    ['exceptional', 'außergewöhnlich'],
    ['exclusive', 'exklusiv|ausschließlich'],
    ['exemplary', 'vorbildlich|exemplarisch'],
    ['extensive', 'ausgedehnt|weitreichend'],
    ['farsighted', 'weitsichtig'],
    ['feasible', 'machbar|durchführbar'],
    ['fierce', 'wild|heftig|erbittert'],
    ['forward-thinking', 'zukunftsorientiert'],
    ['frugal', 'sparsam|genügsam'],
    ['groundbreaking', 'bahnbrechend'],
    ['illicit', 'unerlaubt|illegal'],
    ['impartial', 'unparteiisch|objektiv'],
    ['indispensable', 'unentbehrlich|unverzichtbar'],
    ['inefficient', 'ineffizient'],
    ['influential', 'einflussreich'],
    ['insightful', 'aufschlussreich|tiefgründig'],
    ['obsolete', 'veraltet|überholt'],
    ['outrageous', 'empörend|unerhört'],
    ['painstaking', 'sorgfältig|akribisch'],
    ['pervasive', 'durchdringend|allgegenwärtig'],
    ['plausible', 'plausibel|einleuchtend'],
    ['proactive', 'proaktiv|vorausschauend'],
    ['prolific', 'produktiv|fruchtbar'],
    ['prominent', 'prominent|herausragend'],
    ['prosperous', 'wohlhabend|florierend'],
    ['provocative', 'provokativ'],
    ['receptive', 'empfänglich|aufgeschlossen'],
    ['redundant', 'überflüssig|redundant'],
    ['relentless', 'unerbittlich|beharrlich'],
    ['renowned', 'renommiert|bekannt'],
    ['resilient', 'widerstandsfähig|belastbar'],
    ['resourceful', 'einfallsreich'],
    ['restless', 'ruhelos|unruhig'],
    ['revealing', 'aufschlussreich'],
    ['ruthless', 'rücksichtslos'],
    ['scrutinizing', 'prüfend|kritisch'],
    ['self-sufficient', 'selbstversorgend|autark'],
    ['skeptical', 'skeptisch|zweiflerisch'],
    ['spontaneous', 'spontan'],
    ['straightforward', 'unkompliziert|direkt'],
    ['striking', 'auffällig|bemerkenswert'],
    ['stubborn', 'stur|hartnäckig'],
    ['tenacious', 'hartnäckig|beharrlich'],
    ['thorough', 'gründlich|sorgfältig'],
    ['thoughtful', 'nachdenklich|rücksichtsvoll'],
    ['transparent', 'transparent|durchsichtig'],
    ['trivial', 'trivial|unbedeutend'],
    ['unconventional', 'unkonventionell'],
    ['unpredictable', 'unvorhersehbar'],
    ['urgent', 'dringend'],
    ['versatile', 'vielseitig'],
    ['piano', 'Klavier'],
    ['guitar', 'Gitarre'],
    ['violin', 'Geige|Violine'],
    ['cello', 'Cello'],
    ['trumpet', 'Trompete'],
    ['flute', 'Flöte'],
    ['drum', 'Trommel'],
    ['bass', 'Bass'],
    ['saxophone', 'Saxofon'],
    ['clarinet', 'Klarinette'],
    ['harp', 'Harfe'],
    ['melody', 'Melodie'],
    ['harmony', 'Harmonie'],
    ['rhythm', 'Rhythmus'],
    ['beat', 'Takt|Schlag'],
    ['chord', 'Akkord'],
    ['note', 'Note'],
    ['scale', 'Tonleiter'],
    ['tempo', 'Tempo'],
    ['lyrics', 'Liedtext|Lyrics'],
    ['verse', 'Strophe|Vers'],
    ['chorus', 'Refrain|Chor'],
    ['album', 'Album'],
    ['track', 'Track|Titel'],
    ['playlist', 'Playlist'],
    ['band', 'Band'],
    ['orchestra', 'Orchester'],
    ['conductor', 'Dirigent'],
    ['composer', 'Komponist|Komponistin'],
    ['singer', 'Sänger|Sängerin'],
    ['pop', 'Pop'],
    ['rock', 'Rock'],
    ['jazz', 'Jazz'],
    ['classical', 'klassisch'],
    ['hip hop', 'Hip-Hop'],
    ['electronic', 'elektronisch'],
    ['folk', 'Folk'],
    ['rehearsal', 'Probe|Generalprobe'],
    ['studio', 'Studio'],
    ['microphone', 'Mikrofon'],
    ['fiction', 'Belletristik|Fiktion'],
    ['non-fiction', 'Sachbuch'],
    ['biography', 'Biografie'],
    ['autobiography', 'Autobiografie'],
    ['anthology', 'Anthologie|Sammlung'],
    ['genre', 'Genre|Gattung'],
    ['plot', 'Handlung|Plot'],
    ['character', 'Charakter|Figur'],
    ['protagonist', 'Protagonist|Hauptfigur'],
    ['antagonist', 'Antagonist|Gegenspieler'],
    ['narrator', 'Erzähler'],
    ['monologue', 'Monolog'],
    ['metaphor', 'Metapher'],
    ['simile', 'Vergleich|Gleichnis'],
    ['irony', 'Ironie'],
    ['satire', 'Satire'],
    ['allegory', 'Allegorie'],
    ['symbolism', 'Symbolismus'],
    ['theme', 'Thema'],
    ['setting', 'Schauplatz|Umgebung'],
    ['climax', 'Höhepunkt|Klimax'],
    ['resolution', 'Auflösung'],
    ['chapter', 'Kapitel'],
    ['paragraph', 'Absatz'],
    ['sentence', 'Satz'],
    ['clause', 'Nebensatz|Klausel'],
    ['phrase', 'Phrase|Ausdruck'],
    ['syntax', 'Syntax'],
    ['semantics', 'Semantik'],
    ['phonetics', 'Phonetik'],
    ['morphology', 'Morphologie'],
    ['etymology', 'Etymologie'],
    ['dialect', 'Dialekt'],
    ['accent', 'Akzent'],
    ['idiom', 'Redewendung'],
    ['proverb', 'Sprichwort'],
    ['slang', 'Slang|Umgangssprache'],
    ['jargon', 'Fachsprache|Jargon'],
    ['fluency', 'Fließendheit|Flüssigkeit'],
    ['proficiency', 'Kenntnisse|Kompetenz'],
    ['bilingual', 'zweisprachig'],
    ['multilingual', 'mehrsprachig'],
    ['native speaker', 'Muttersprachler|Muttersprachlerin'],
    ['mother tongue', 'Muttersprache'],
    ['second language', 'Zweitsprache'],
    ['dictionary', 'Wörterbuch'],
    ['thesaurus', 'Thesaurus|Synonymwörterbuch'],
    ['architecture', 'Architektur'],
    ['construction', 'Bau|Konstruktion'],
    ['frame', 'Rahmen|Gerüst'],
    ['beam', 'Balken|Träger'],
    ['column', 'Säule'],
    ['arch', 'Bogen'],
    ['dome', 'Kuppel'],
    ['tower', 'Turm'],
    ['renovation', 'Renovierung'],
    ['restoration', 'Restaurierung'],
    ['demolition', 'Abriss|Demolierung'],
    ['blueprint', 'Bauplan|Blueprint'],
    ['floor plan', 'Grundriss'],
    ['facade', 'Fassade'],
    ['interior', 'Innenraum|Inneres'],
    ['exterior', 'Außenbereich|Äußeres'],
    ['landscape', 'Landschaft|Landschaftsgestaltung'],
    ['urban planning', 'Stadtplanung'],
    ['zoning', 'Zonierung|Flächennutzung'],
    ['permit', 'Genehmigung|Erlaubnis'],
    ['contractor', 'Auftragnehmer|Bauunternehmer'],
    ['architect', 'Architekt|Architektin'],
    ['engineer', 'Ingenieur|Ingenieurin'],
    ['surveyor', 'Vermesser|Gutachter'],
    ['attitude', 'Einstellung|Haltung'],
    ['personality', 'Persönlichkeit'],
    ['trait', 'Eigenschaft|Merkmal'],
    ['cognition', 'Kognition|Denken'],
    ['emotion', 'Emotion|Gefühl'],
    ['instinct', 'Instinkt'],
    ['habit', 'Gewohnheit'],
    ['addiction', 'Sucht|Abhängigkeit'],
    ['phobia', 'Phobie|Angst'],
    ['trauma', 'Trauma'],
    ['burnout', 'Burnout|Erschöpfung'],
    ['resilience', 'Resilienz|Belastbarkeit'],
    ['mindfulness', 'Achtsamkeit'],
    ['meditation', 'Meditation'],
    ['counseling', 'Beratung'],
    ['psychiatry', 'Psychiatrie'],
    ['psychology', 'Psychologie'],
    ['subconscious', 'Unterbewusstsein'],
    ['unconscious', 'Unbewusst'],
    ['bias', 'Vorurteil|Verzerrung'],
    ['stereotype', 'Stereotyp'],
    ['prejudice', 'Vorurteil'],
    ['self-esteem', 'Selbstwertgefühl'],
    ['self-confidence', 'Selbstvertrauen'],
    ['assertiveness', 'Durchsetzungsvermögen|Selbstbehauptung'],
    ['introvert', 'Introvertierter'],
    ['extrovert', 'Extrovertierter'],
    ['sympathy', 'Mitgefühl|Sympathie'],
    ['compassion', 'Mitgefühl|Mitleid'],
    ['altruism', 'Altruismus|Uneigennützigkeit'],
    ['ego', 'Ego|Ich'],
    ['identity', 'Identität'],
    ['self-image', 'Selbstbild'],
    ['civilization', 'Zivilisation'],
    ['medieval', 'mittelalterlich'],
    ['renaissance', 'Renaissance'],
    ['empire', 'Reich|Kaiserreich'],
    ['dynasty', 'Dynastie'],
    ['monarchy', 'Monarchie'],
    ['republic', 'Republik'],
    ['colonialism', 'Kolonialismus'],
    ['imperialism', 'Imperialismus'],
    ['nationalism', 'Nationalismus'],
    ['fascism', 'Faschismus'],
    ['communism', 'Kommunismus'],
    ['capitalism', 'Kapitalismus'],
    ['dictatorship', 'Diktatur'],
    ['totalitarianism', 'Totalitarismus'],
    ['genocide', 'Völkermord|Genozid'],
    ['holocaust', 'Holocaust'],
    ['war crimes', 'Kriegsverbrechen'],
    ['armistice', 'Waffenstillstand'],
    ['liberation', 'Befreiung'],
    ['archaeology', 'Archäologie'],
    ['artifact', 'Artefakt'],
    ['ruin', 'Ruine'],
    ['heritage', 'Erbe|Kulturerbe'],
    ['mythology', 'Mythologie'],
    ['legend', 'Legende'],
    ['folklore', 'Folklore'],
    ['statute', 'Gesetz|Statut'],
    ['ordinance', 'Verordnung'],
    ['violation', 'Verstoß|Verletzung'],
    ['penalty', 'Strafe|Sanktion'],
    ['fine', 'Geldstrafe|Bußgeld'],
    ['acquittal', 'Freispruch'],
    ['conviction', 'Verurteilung|Überzeugung'],
    ['appeal', 'Berufung|Einspruch'],
    ['verdict', 'Urteil|Entscheidung'],
    ['testimony', 'Aussage|Zeugnis'],
    ['witness', 'Zeuge|Zeugin'],
    ['suspect', 'Verdächtiger|Verdächtige'],
    ['defendant', 'Angeklagter|Beklagter'],
    ['plaintiff', 'Kläger'],
    ['prosecution', 'Strafverfolgung|Anklage'],
    ['defense', 'Verteidigung'],
    ['attorney', 'Anwalt|Rechtsanwalt'],
    ['solicitor', 'Rechtsanwalt'],
    ['barrister', 'Anwalt'],
    ['jurisdiction', 'Gerichtsbarkeit|Zuständigkeit'],
    ['litigation', 'Rechtsstreit'],
    ['settlement', 'Vergleich|Einigung'],
    ['arbitration', 'Schiedsverfahren'],
    ['mediation', 'Vermittlung|Mediation'],
    ['liability', 'Haftung|Verantwortung'],
    ['negligence', 'Fahrlässigkeit'],
    ['fraud', 'Betrug'],
    ['bribery', 'Bestechung'],
    ['embezzlement', 'Veruntreuung'],
    ['intellectual property', 'geistiges Eigentum'],
    ['addition', 'Addition|Zusammenzählen'],
    ['subtraction', 'Subtraktion|Abziehen'],
    ['multiplication', 'Multiplikation|Malnehmen'],
    ['division', 'Division|Teilen'],
    ['fraction', 'Bruch|Bruchteil'],
    ['decimal', 'Dezimalzahl'],
    ['ratio', 'Verhältnis'],
    ['variable', 'Variable'],
    ['constant', 'Konstante'],
    ['graph', 'Graph|Diagramm'],
    ['coordinate', 'Koordinate'],
    ['axis', 'Achse'],
    ['triangle', 'Dreieck'],
    ['square', 'Quadrat'],
    ['circle', 'Kreis'],
    ['rectangle', 'Rechteck'],
    ['polygon', 'Polygon|Vieleck'],
    ['sphere', 'Kugel'],
    ['cube', 'Würfel'],
    ['cylinder', 'Zylinder'],
    ['cone', 'Kegel'],
    ['theorem', 'Theorem|Satz'],
    ['proof', 'Beweis'],
    ['logic', 'Logik'],
    ['premise', 'Prämisse|Voraussetzung'],
    ['inference', 'Schlussfolgerung'],
    ['paradox', 'Paradox|Widerspruch'],
    ['axiom', 'Axiom'],
    ['sequence', 'Folge|Reihenfolge'],
    ['pattern', 'Muster'],
    ['symmetry', 'Symmetrie'],
    ['mean', 'Mittelwert|Durchschnitt'],
    ['median', 'Median'],
    ['mode', 'Modus|Modalwert'],
    ['standard deviation', 'Standardabweichung'],
    ['sample', 'Stichprobe'],
    ['absence', 'Abwesenheit|Fehlen'],
    ['abundance', 'Fülle|Überfluss'],
    ['acceptance', 'Annahme|Akzeptanz'],
    ['accident', 'Unfall|Zufall'],
    ['accuracy', 'Genauigkeit|Präzision'],
    ['accusation', 'Beschuldigung|Anklage'],
    ['action', 'Aktion|Handlung'],
    ['activity', 'Aktivität|Tätigkeit'],
    ['advance', 'Fortschritt|Vorschuss'],
    ['affair', 'Angelegenheit|Affäre'],
    ['age', 'Alter|Zeitalter'],
    ['agency', 'Agentur|Handlungsfähigkeit'],
    ['aim', 'Ziel|Absicht'],
    ['alarm', 'Alarm|Warnung'],
    ['appointment', 'Termin|Ernennung'],
    ['appreciation', 'Wertschätzung|Anerkennung'],
    ['arrangement', 'Vereinbarung|Anordnung'],
    ['asset', 'Vermögenswert|Vorteil'],
    ['attraction', 'Anziehung|Attraktion'],
    ['backbone', 'Rückgrat'],
    ['background', 'Hintergrund|Herkunft'],
    ['balance', 'Gleichgewicht|Bilanz'],
    ['barrier', 'Barriere|Hindernis'],
    ['basis', 'Grundlage|Basis'],
    ['belief', 'Überzeugung|Glaube'],
    ['blame', 'Schuld|Vorwurf'],
    ['bond', 'Bindung|Anleihe'],
    ['boundary', 'Grenze'],
    ['breakthrough', 'Durchbruch'],
    ['burden', 'Last|Bürde'],
    ['campaign', 'Kampagne'],
    ['capability', 'Fähigkeit|Kapazität'],
    ['carrier', 'Träger'],
    ['cause', 'Ursache|Grund'],
    ['center', 'Zentrum|Mittelpunkt'],
    ['channel', 'Kanal'],
    ['charge', 'Gebühr|Ladung'],
    ['choice', 'Wahl|Entscheidung'],
    ['claim', 'Anspruch|Behauptung'],
    ['code', 'Code|Schlüssel'],
    ['coherence', 'Kohärenz'],
    ['communication', 'Kommunikation'],
    ['concern', 'Sorge|Anliegen'],
    ['connection', 'Verbindung'],
    ['contrast', 'Kontrast|Gegensatz'],
    ['convenience', 'Bequemlichkeit'],
    ['cycle', 'Zyklus|Kreislauf'],
    ['damage', 'Schaden'],
    ['decision', 'Entscheidung'],
    ['denial', 'Verleugnung|Ablehnung'],
  ];
}